### ISSUE TITLE
Apps not loading

### ISSUE THREAD

**Issue by jplevyak** [sandstorm-io/sandstorm#1048]
I did a local install (vzite.sandcats.io) and a dev install  and in both cases when I install an app (e.g. the Go game) the icon for the app does not appear and when I attempt to create a Grain it just spins forever with the loading image.

I am getting this message in the log repeatedly:

Downloading app: https://app-index.sandstorm.io/packages/850e35bc352b15dac6af0592d0fc1e73
App ready: 850e35bc352b15dac6af0592d0fc1e73
fetching keybase 6B7486EA873576FD72845C5E50E4D7384B1B4D65
Exception while invoking method 'keepSessionAlive' Error: remote exception: Peer disconnected.
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:398:15)
    at waitPromise (app/server/proxy.js:124:35)
    at [object Object].Meteor.methods.keepSessionAlive (app/server/proxy.js:302:7)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/ddp/livedata_server.js:546:1
    - - - - -
Downloading app: https://app-index.sandstorm.io/packages/5a060d87bcb07bfee3b0f0dbaff8395a
App ready: 5a060d87bcb07bfee3b0f0dbaff8395a
fetching keybase 783531F926C513050520A33E5C6488AEAD045C21
Exception while invoking method 'keepSessionAlive' Error: remote exception: Peer disconnected.
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:398:15)
    at waitPromise (app/server/proxy.js:124:35)
    at [object Object].Meteor.methods.keepSessionAlive (app/server/proxy.js:302:7)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/ddp/livedata_server.js:546:1
    - - - - -
Exception while invoking method 'keepSessionAlive' Error: remote exception: Peer disconnected.
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:398:15)
    at waitPromise (app/server/proxy.js:124:35)
    at [object Object].Meteor.methods.keepSessionAlive (app/server/proxy.js:302:7)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    at packages/ddp/livedata_server.js:546:1

etc. etc. It repeat periodically.

**Comment by kentonv** [comment]
The `keepSessionAlive` error is a red herring -- it's an unrelated bug that typically doesn't actually hurt anything.

The problem you describe sounds instead like your wildcard host is for some reason not working. The apps (and app icons) are served off of the wildcard, not the main hostname, and it's common to see exactly what you're seeing in cases where this is misconfigured.

But it's very strange that it would be misconfigured when using Sandcats. From here, it looks like vzite.sandcats.io is in fact working fine.

Is it possible you did something like overrode vzite.sandcats.io it your /etc/hosts, e.g. to get around a broken router that doesn't support loopback routing? If so you'll need to map *.vzite.sandcats.io as well -- but unfortunately /etc/hosts does not support wildcards.

**Comment by jplevyak** [comment]
That is precisely the situation.  I am sitting behind dd-wrt which is sitting behind a comcast router and dd-wrt doesn't really know the real WAN address so I overroad in /etc/hosts.

Thanx for the information.  I'll see what I can do.

**Comment by paulproteus** [comment]
Oh, interesting. I guess you're behind double-NAT, which is making this
extra difficult.

One thing you can try (though it's not necessarily something that'll be of
use generally to everyone) -- consider configuring the dd-wrt box to use
the Comcast box for DHCP etc.
http://www.asheesh.org/note/sysop/wifi-repeaters.html is my diagram on how
to do that.

Then your dd-wrt box can provide wifi, but not be authoritative for DHCP,
and that should hopefully give you the best of both worlds.

Let me know if you try that, and if it works out for you!

**Comment by jplevyak** [comment]
My solution was to add a line to "Additional DNSMasq Options" on the DD WRT menu Services::DNSMasq:

address=/vzite.sandcats.io/192.168.1.207

(note, leave off the -- before the address option).  This maps vzite.sandcats.io and all subdomains to the address of the server on my LAN.

All good now. Thanx!

**Comment by paulproteus** [comment]
Great!​

**Comment by memento** [comment]
Hello !
Same problem [here](https://github.com/sandstorm-io/sandstorm/issues/1232#issuecomment-176107667) (maybe ?) : 

No icon for apps and spinning forever when creating a grain.
Though, I don't have anything wrong in log.
Any clue ?

**Comment by memento** [comment]
Anyone ?

**Comment by ocdtrekkie** [comment]
@memento As the above said, it's very likely to be an issue with your DNS not being setup for the wildcard.

**Comment by memento** [comment]
Actually, I re-routed the ports 80 and 443 directly on the debian server (with sandstorm on it) and it works, so I don't think it has anything to do with the DNS. By the way, when you say DNS, as I don't have a DNS server on my server, what did you suggest I should do ? I don't owe the domain ___thing.sandcats.io___. So, no DNS registar acount configuration.

**Comment by criskolkman** [comment]
Hello,

I do have the same problem as described here.
Only thing is I don't see anything come up in the sandstorm logs.
It doesn't seem to be a problem with DNS.
