### ISSUE TITLE
All existing grains 500 error

### ISSUE THREAD

**Issue by mnutt** [sandstorm-io/sandstorm#1123]
I'm on the dev channel and earlier today got the update from v0.128 to v0.129. Now all of my existing grains throw 500 errors when trying to access, while new grains work fine.

The errors I see in sandstorm.log:

```
capnp/rpc.c++:122: info: returning failure over rpc; exception = kj/async-io.c++:120: failed: expected result >= minBytes; Premature EOF
stack: 0x44ea82 0x415cd0 0x415850 0x414c60 0x413500 0x4ae3c0
capnp/rpc.c++:122: info: returning failure over rpc; exception = kj/async-io.c++:120: failed: expected result >= minBytes; Premature EOF
stack: 0x44ea82 0x415cd0 0x415850 0x414c60 0x413500 0x4c8f90 0x4cd6d0 0x4ae3c0
capnp/rpc.c++:122: info: returning failure over rpc; exception = kj/async-io.c++:120: failed: expected result >= minBytes; Premature EOF
stack: 0x44ea82 0x415cd0 0x415850 0x414c60 0x413500 0x4c8f90 0x4cd6d0 0x4ae3c0
No such grain: wC7YogZNkWxfokGC9WFHCq
capnp/rpc.c++:122: info: returning failure over rpc; exception = kj/async-io.c++:120: failed: expected result >= minBytes; Premature EOF
stack: 0x44ea82 0x415cd0 0x415850 0x414c60 0x413a40 0x4ae3c0
No such grain: Mp6kWrpgFop3TPSsv9MuCM
capnp/rpc.c++:122: info: returning failure over rpc; exception = kj/async-io.c++:120: failed: expected result >= minBytes; Premature EOF
stack: 0x44ea82 0x415cd0 0x415850 0x414c60 0x413a40 0x4ae3c0
Exception while invoking method 'openSession' Error: remote exception: expected result >= minBytes; Premature EOF
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:398:15)
    at waitPromise (packages/sandstorm-backend/sandstorm-backend.js:47:1)
    at [object Object].SandstormBackend.startGrainInternal (packages/sandstorm-backend/sandstorm-backend.js:220:1)
    at [object Object].SandstormBackend.continueGrain (packages/sandstorm-backend/sandstorm-backend.js:183:1)
    at [object Object].SandstormBackend.openSessionInternal (packages/sandstorm-backend/sandstorm-backend.js:282:1)
    at [object Object].Meteor.methods.openSession (app/server/proxy.js:207:26)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    - - - - -
Exception while invoking method 'openSession' Error: remote exception: expected result >= minBytes; Premature EOF
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:398:15)
    at waitPromise (packages/sandstorm-backend/sandstorm-backend.js:47:1)
    at [object Object].SandstormBackend.openSessionInternal (packages/sandstorm-backend/sandstorm-backend.js:280:1)
    at [object Object].Meteor.methods.openSession (app/server/proxy.js:207:26)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
    - - - - -
```

**Comment by mnutt** [comment]
Ok, I shot myself in the foot on this one. I had mounted the grains/ directory from another volume, which wasn't really even working anyway. Putting it all back on one volume solved my issue. I'd still really like to be able to store grains on a different volume, but that's for another time.

**Comment by paulproteus** [comment]
Nod. ​Curious - why not "just" move all of /opt/sandstorm to the other
volume?

**Comment by mnutt** [comment]
The initial reasoning was to try to put everything _but_ grains on provisioned IOPS SSD and the grains themselves on a very large magnetic disk. I plan on having hundreds of GBs of data synced in Davros.

It'd be slightly nice to have sandstorm's mongodb on SSD, but at this point I'm probably prematurely optimizing. I'm going to move all of sandstorm to magnetic and see how that goes.
