### ISSUE TITLE
Crash in pre-meteor.js on req.headers.host not being a string

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#1328]
On one of my Sandstorm self-installs, I find the following in the log.

```
/programs/server/app/server/pre-meteor.js:425
    var hostname = req.headers.host.split(":")[0];
                                    ^
TypeError: Cannot call method 'split' of undefined
    at dispatchToMeteorOrStaticPublishing (server/pre-meteor.js:425:1)
    at Server.redirectToMeteorOrServeStaticPublishing (server/pre-meteor.js:415:1)
    at Server.emit (events.js:98:17)
    at HTTPParser.parser.onIncoming (http.js:2109:12)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
    at Socket.socket.ondata (http.js:1967:22)
    at TCP.onread (net.js:528:27)
** Front-end died! Restarting it...
```

We/I should fix this.

**Comment by kentonv** [comment]
Noting, of course, that without a Host header the best we can do is return a 404 rather than an exception.
