### ISSUE TITLE
MongoDB monitoring via Munin

### ISSUE THREAD

**Issue by zeigerpuppy** [sandstorm-io/sandstorm#1704]
I am trying to do some performance monitoring using Munin.
There's a good doc here on how to set it up: https://docs.mongodb.org/ecosystem/tools/munin/
However, I am unable to connect to the sandstorm mongodb instance due to permission issues.
Where are the login credentials for the mongodb instance stored?
The string needed for munin is:

```
[mongo_*]
env.MONGO_DB_URI mongodb://user:password@host:port/dbname
```

**Comment by paulproteus** [comment]
Hi zeigerpuppy,

You can find a mongo password here on a typical Sandstorm
install: /opt/sandstorm/var/mongo/passwd

For the port number, you'll find that in: /opt/sandstorm/sandstorm.conf

For a username, use: sandstorm

Let me know if that helps!

​

**Comment by zeigerpuppy** [comment]
Thanks, it looks closer,
I have used the setting (password replaced with /opt/sandstorm/var/mongo/passwd ):
```
[mongo_*]
env.MONGO_DB_URI mongodb://sandstorm:password@127.0.0.1:6081/meteor
```

however, I still appear to only get partial access to stats, the pymongo error is:

```
Traceback (most recent call last):
  File "/etc/munin/plugins/mongo_ops", line 54, in <module>
    doData()
  File "/etc/munin/plugins/mongo_ops", line 20, in doData
    ss = getServerStatus()
  File "/etc/munin/plugins/mongo_ops", line 16, in getServerStatus
    return c.admin.command('serverStatus', workingSet=True)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/database.py", line 478, in command
    with client._socket_for_reads(read_preference) as (sock_info, slave_ok):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 752, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 718, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/server.py", line 152, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 541, in get_socket
    sock_info.check_auth(all_credentials)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 306, in check_auth
    auth.authenticate(credentials, self)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 436, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 418, in _authenticate_default
    return _authenticate_mongo_cr(credentials, sock_info)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/auth.py", line 411, in _authenticate_mongo_cr
    sock_info.command(source, query)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 213, in command
    read_concern)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/network.py", line 99, in command
    helpers._check_command_response(response_doc, None, allowable_errors)
  File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 196, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: auth failed
```

**Comment by paulproteus** [comment]
Hi! I wonder if some MongoDB stats require a root account. I don't know
much about MongoDB. Can you tell me what specific query you're running?
Then I can search the MongoDB docs to find out what privilege level that
query requires.

**Comment by zeigerpuppy** [comment]
Here's an example of one of the plugins: https://github.com/comerford/mongo-munin/blob/master/mongo_btree
It's using pymongo
It looks like it's setting the URL in:
```
c = pymongo.MongoClient(os.environ['MONGO_DB_URI'])
```
and then I think the query is:
```

return getServerStatus()["indexCounters"]
```


To test, one can run:
```
munin-run mongo_btree
```
