### ISSUE TITLE
Mailgun Setup

### ISSUE THREAD

**Issue by NickBroza** [sandstorm-io/sandstorm#1880]
Currently I am having problems setting up Mailgun with Sandstorm. I've tried using smtp://mailer%40xxxxxx.com:password@smtp.mailgun.org. I also set the relay port to 25 and the username to "mailer@xxxxxx.com", and also the password to "password". I didn't see much on setting up Mailgun in the documentation so this would be a huge help!

**Comment by zarvox** [comment]
Hmmm, that's surprising.  I think other folks have previously reported success with Mailgun.

As noted (albeit briefly) in https://docs.sandstorm.io/en/latest/administering/email/, `MAIL_URL` in `sandstorm.conf` is deprecated and changes to `MAIL_URL` will not have any effect on how the server attempts to send mail, so make sure you're configuring things through the admin UI.

Do you see anything in the log when you try to send a test email?  That could help us track down what specifically is going awry.  You can find the log in the web UI under Admin Settings -> Log, or at `/opt/sandstorm/var/log/sandstorm.log` if you're looking at it from a command line on your server.

**Comment by NickBroza** [comment]
When I attempt to send a test email to myself, it says
![error](https://cloud.githubusercontent.com/assets/4249043/14660288/16b13322-0672-11e6-890d-f8635fe701d2.JPG)


Log:
  at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:126:16)
Exception while invoking method 'testSend' Error: getaddrinfo ENOTFOUND
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:420:15)
    at smtpSend (packages/sandstorm-email/email.js:90:35)
    at Object.SandstormEmail.rawSend (packages/sandstorm-email/email.js:187:5)
    at Object.SandstormEmail.send (packages/sandstorm-email/email.js:168:18)
    at [object Object].testSend (server/admin-server.js:268:20)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor.js:1100:17)

Also, as a side note, I have arno-iptables-firewall installed onto my server, but all the required ports are opened, as well as forwarded on my router.

**Comment by zarvox** [comment]
Ahhh, the Sandstorm instance is unable to resolve the hostname (which you mentioned above is `smtp.mailgun.org`) into an IP address to make an outgoing connection.

Do you have working DNS on your server?  Try `ping smtp.mailgun.org` or `host smtp.mailgun.org` from your server.  The output looks like this for me:

```
(18:52:56) zarvox@pegasus ~ $ host smtp.mailgun.org
smtp.mailgun.org has address 50.56.21.178
smtp.mailgun.org has address 104.130.177.23
(18:52:58) zarvox@pegasus ~ $ ping smtp.mailgun.org
PING smtp.mailgun.org (50.56.21.178) 56(84) bytes of data.
64 bytes from smtp.mailgun.org (50.56.21.178): icmp_seq=1 ttl=234 time=85.0 ms
64 bytes from smtp.mailgun.org (50.56.21.178): icmp_seq=2 ttl=234 time=83.7 ms
```

Make sure your firewall config allows outgoing UDP and TCP traffic with destination port 53 (DNS), as well as related traffic (for the UDP replies).

**Comment by NickBroza** [comment]
When I ping smtp.mailgun.org, I get essentially the same thing as your output. I let port 53/related ports through my firewall (both UDP and TCP). I also tried forwarding the ports with no avail. Also, my ISP is not blocking any of the ports. Thanks for your help!

**Comment by paulproteus** [comment]
Hi @NickBroza ,

If this is still a problem, and you have root on the server, please try to run the following diagnostics:

```
# First: Get root
sudo su -
# Second: Get a nodejs shell within the Sandstorm self-containerized context
nsenter --target $(ps auxw | grep sandstorm-main.js | grep -v grep | awk '{ print $2; }') --wd --mount --net --ipc --uts --pid /bin/node
# Finally: Attempt to do a DNS lookup from this context
var dns = require('dns'); dns.lookup('smtp.mailgun.org', function(err, address, family) { console.log(JSON.stringify({err: err || "No error!", address: address, family: family})); });
```

If you can give me the output of the last command, that will be very helpful. My guess is that you'll find that the DNS resolution fails within the context of Sandstorm, and at that point, we'll have to figure out how to make it _not_ fail.

Slightly sorry that the debugging procedure is so complicated.

We've seen similar issues crop up before, due to Sandstorm's self-containerization interacting poorly with people's system DNS configurations.

See also:

- https://github.com/sandstorm-io/sandstorm/pull/1030
- https://github.com/sandstorm-io/sandstorm/issues/895

**Comment by zarvox** [comment]
Oh yeah, I forgot about the gyrations we go through to reuse the host's DNS resolution.  @paulproteus thanks for reminding me about that!

Other potentially helpful information you could provide would be the output of running

```bash
ls -l /etc/resolv.conf /etc/nsswitch.conf
cat /etc/resolv.conf
cat /etc/nsswitch.conf | grep hosts
```

from a shell on the server.

If `/etc/resolv.conf` or `/etc/nsswitch.conf` is a symlink that points outside of `/etc/`, we might be failing to link its into Sandstorm's container.  Or if your nsswitch relies on a name service that we don't support in our libc, that could also cause resolution failure.
