### ISSUE TITLE
make stylecheck produces no useful output with jscs 3.0.3

### ISSUE THREAD

**Issue by mitar** [sandstorm-io/sandstorm#1933]
Example:

```
make stylecheck
cd shell && jscs .
Config values to remove in 3.0:
The `esnext` option is enabled by default.
The `verbose` option is enabled by default.
make: *** [stylecheck] Error 1
```

**Comment by mitar** [comment]
If I remove `verbose` and `esnext` output and , I get output, but also a strange error at the end:

```
TypeError: Cannot read property 'replace' of undefined
    at renderLine (/usr/local/lib/node_modules/jscs/lib/errors.js:266:16)
    at Object.Errors.explainError (/usr/local/lib/node_modules/jscs/lib/errors.js:197:13)
    at /usr/local/lib/node_modules/jscs/lib/reporters/text.js:16:36
    at Array.forEach (native)
    at /usr/local/lib/node_modules/jscs/lib/reporters/text.js:14:35
    at Array.forEach (native)
    at Object.module.exports [as writer] (/usr/local/lib/node_modules/jscs/lib/reporters/text.js:9:22)
    at /usr/local/lib/node_modules/jscs/lib/cli.js:149:18
    at Array.<anonymous> (/usr/local/lib/node_modules/jscs/node_modules/vow/lib/vow.js:712:56)
    at Immediate.callFns [as _onImmediate] (/usr/local/lib/node_modules/jscs/node_modules/vow/lib/vow.js:23:35)
```

**Comment by zarvox** [comment]
Huh, if I remove verbose and esnext, I get a bunch of complaints that are probably JSCS getting more precise about rules over time, followed by that same stacktrace.

Looks possibly related to https://github.com/jscs-dev/node-jscs/issues/1828 ?  JSCS is definitely tripping up on something and failing internally.  I guess my reply is "try an older version".

**Comment by mitar** [comment]
Yes, I am using old version for now. Just wanted to report.
