### ISSUE TITLE
Setting up Email SMTP errror 500 internal server error

### ISSUE THREAD

**Issue by OliverHi** [sandstorm-io/sandstorm#1955]
Hi there,

I love the idea of sandstorm so I tried to install it on a server of mine to test it. I ran the installer, (signed up for a domain name) and got the temporary link to create a first account. Logged into that and started the configuration wizard. I want to enable login via email (and email only if possible for now) so I had to fill in the SMTP data. I did that and double/tripple checked them. I am using the same data as e.g. in thunderbird where it works without a problem (the provider is hosteurope if thats important).
Whenever I try to send an email via the test button I get a "Error 500 internal server error" error message.

I could not find any info for this and I can't use the sandstorm instance without the email.

Any idea what might be wrong? How do I get more infos? Is there a log for this?

**Comment by zarvox** [comment]
Hi!  Thanks for trying Sandstorm.

I'm not sure exactly what's going wrong, but if you can paste or gist the contents of `/opt/sandstorm/var/log/sandstorm.log`, that would be super helpful.

I've also filed #1956 about making debugging this failure mode more straightforward.

**Comment by OliverHi** [comment]
Hi, thanks for the fast answer and the new ticket. I think this is a good idea.

I found a lot of these errors in the log:
`Exception while invoking method 'testSend' AuthError: Invalid login - 535 Incorrect authentication data
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:420:15)
    at smtpSend (packages/sandstorm-email/email.js:90:35)
    at Object.SandstormEmail.rawSend (packages/sandstorm-email/email.js:187:5)
    at Object.SandstormEmail.send (packages/sandstorm-email/email.js:168:18)
    at [object Object].testSend (server/admin-server.js:268:20)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
    - - - - -
    at SMTPClient._actionAUTHComplete (/programs/server/npm/node_modules/meteor/sandstorm-email/node_modules/simplesmtp/lib/client.js:826:23)
    at SMTPClient._onData (/programs/server/npm/node_modules/meteor/sandstorm-email/node_modules/simplesmtp/lib/client.js:329:29)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
    at process._tickCallback (node.js:458:13)`

This is the main one I guess. I will check the data again but we used the exact same username/pw/SMTP server data for other services and it worked just fine... Any ideas?

**Comment by zarvox** [comment]
Yeah, it appears that the remote mailserver is explicitly rejecting the login, which is surprising if you've successfully used that set of credentials elsewhere.  Do the username or password contain a non-ASCII-clean character, or something that you've already escaped, or something else possibly unusual?  Do you need to possibly add or remove an `@example.com` to the username in question?

Selecting port 465 should be sufficient to make Sandstorm require an encrypted connection, see [email.js](https://github.com/sandstorm-io/sandstorm/blob/master/shell/packages/sandstorm-email/email.js#L22) for implementation details.

**Comment by OliverHi** [comment]
Thank you for your help, it is actually working now! I don't really know what I changed, I guess I misstyped the first few times somehow.
I still think it's a good idea to show something like "wrong login"/"login refused"/... instead of "internal server error" ;)
