### ISSUE TITLE
Default User-Agent to HTTPSession Requests

### ISSUE THREAD

**Issue by frioux** [sandstorm-io/sandstorm#2018]
Currently there's no user agent defaulted by meteor, so there's no user agent for sandstorm.  This can cause problems as it's such a common header that it is almost defacto required.  Should be pretty easy; probably making it Sandstorm/$version is good enough, though something like ApplicationName/$version (Sandstorm/$version) might be useful if that's not considered a privacy violation.

**Comment by frioux** [comment]
```
11:10:13            frew | so this is bizarre
11:10:23            frew | my feed reader on the oasis gets a 403 from one of the feeds
11:10:25            frew | but I don't locally
11:11:17            frew | does anyone know what the javascript stuff is about in the log for
                         | TTRSS?
11:11:34            frew | TTRSS is php so I have no idea why there'd be a JS stacktrace in the
                         | logs
11:12:32            frew | https://gist.github.com/frioux/ce08da44f64ddcb7fb285e9fa0c9174c   
11:12:35            frew | if interested
11:13:41            frew | it has to have something to do with the meteor stuff
11:13:52            frew | that's my guess anyway
11:14:27             cmr | frew: judging by the presence of hack-session and streams, I'd guess
                         | that's from Sandstorm, not the app.
11:14:31          zarvox | That timestamp is suspect
11:14:44            frew | zarvox: I was assuming that in sandstorm the app doesn't get access
                         | to the actual time
11:14:57          zarvox | perhaps
11:15:24          zarvox | this is using the httpGet call on HackSessionContext?
11:15:33            frew | I have to assume so
11:15:45            frew | the rss reader seems to be doing that to access feeds?
11:17:09          zarvox | the code suggests that the 403 is coming from the remote server
11:17:17            frew | yeah I know
11:17:33            frew | but I can't see that here.  I mean, you can try to hit that url  
                         | yourself and it should work
11:17:50          zarvox | yes, curl seems to work okay
11:18:14            frew | I'm making a little proxy myself to fix it but I suspect there's
                         | something weird about the meteor thing to cause this.
11:18:25            frew | I was wondering if it was na https thing
11:19:33          zarvox | my browser does not like their cert
11:19:45            frew | yeah that's what I saw.
11:19:46          zarvox | probably the sandstorm shell does not like their cert either   
11:20:03            frew | yeah; that's exactly what I was thinking is the issue; I just
                         | figured making it a 403 seems unhelpful
11:20:17          zarvox | (and the request library we're using probably translates that into a
                         | 403?)   
11:20:28            frew | apparently
11:22:40         sknebel | wouldn't all HTTPS verification fail with that timestamp? or is that
                         | a different layer?
11:23:03            frew | sknebel: I had that same thought, but I think that timestamp is
                         | inside the container and that the https happens in the browser
11:27:18            frew | ok well I fixed it by writing my own little ghetto proxy
11:27:29            frew | but it would be nice for this to be more obvious in the future
11:55:07            frew | so the guy who runs that blog told me that this is a symptom of not
                         | having a User-Agent?
11:55:15            frew | is that something that would be sandstorm's fault or TTRSS'?
11:55:27            frew | I know that the TTRSS code is super sloppy with stuff like that
11:56:12         asheesh | Howdy frew
11:56:19         asheesh | Hilarious re: symptom of no user-agent
11:56:25         asheesh | That's probably Sanstorm; let me pull up the code.
11:57:28            frew | asheesh: good morning :) (or w/e time it is for you)
11:57:46         asheesh | Per shell/server/hack-session.js: , https://github.com/sandstorm-io/
                         | sandstorm/blob/4ecf998cd700deb1024bbffe57d948610ec3a019/shell/server
                         | /hack-session.js#L282
11:57:49         asheesh | https://github.com/sandstorm-io/sandstorm/search?q=httpget
11:58:50         asheesh | Seemingly we delegate to http://docs.meteor.com/api/http.html which
                         | I don't know what headers it sends, but could be no user-agent by
                         | default, let me see...
11:59:29         asheesh | https://github.com/meteor/meteor/blob/abd574f38008b45f5e2a6bc322b10b
                         | cdde44763a/packages/http/httpcall_server.js#L37 seemingly no
                         | user-agent by default
11:59:31            frew | so am I correct that if there is no browser the application cannot
                         | reach out at all?
12:00:48         asheesh | Sandstorm apps' server-side code have a concept of a "session."
12:00:57         asheesh | Today, that is a "HackSession" because we don't like the quality of
                         | the session.
12:01:34         asheesh | The server-side code of the app uses this Sandstorm session to ask
                         | questions like (a) which Sandstorm user is viewing this? and (b) hey
                         | Sandstorm make an outbound HTTP GET call
12:01:54         asheesh | The session expires over time if you're not looking at it in a web
                         | browser, but it's not literally a connection to your web browser.
12:02:14         asheesh | I hope that helps somewhat. Seems like I should write a doc at some
                         | point about what the "Session" is for Sandstorm.
13:14:06            frew | ah ok
13:14:17            frew | so if I connect via a non-web browser client, over http, it can
                         | still make requests
13:18:03         asheesh | In that case you have an ApiSession, which is slightly different;
                         | let me check if it can make requests based on that.
13:18:45         asheesh | OK, the answer is yes, it can make requests based on that!
13:18:53         asheesh | (This is because ApiSession extends WebSession.)
13:21:13            frew | makes sense
13:21:24            frew | ok I assumed the browser was making requests on behalf of the
                         | application
13:21:28            frew | which seemed crazy bizarre to me
13:21:48            frew | but could be sensible if you wanted to block the app from doing
                         | things on it's own I guess
13:22:11            frew | asheesh: should I open an issue to default a User-Agent?
13:26:08         asheesh | +1 frew, thanks for offering to do that!
```

And the referenced gist:
```
[17:01:10/83] Base feed: https://utcc.utoronto.ca/~cks/space/blog/?atom
[17:01:10/83]  => 1970-01-01 00:00:00, 63 1
*** Uncaught exception ***
(remote):0: failed: remote exception: remote exception: remote exception: remote exception: remote exception: remote exception: Error: Status code 403 received in response.
    at ClientRequest.<anonymous> (server/hack-session.js:312:19)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient (http.js:1744:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:152:23)
    at CleartextStream.socketOnData (http.js:1639:20)
    at CleartextStream.read [as _read] (tls.js:514:12)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)
    at Socket.emit (events.js:92:17)
stack: 0x438ec0 0x41ae10 0x4194a0 0x402730 0x40303c 0x402953 0x4027cd 0x4b03b1
[17:01:10/83]     0.3232 (sec)
```

**Comment by bcarnes** [comment]
Seems like a similar issue is causing ttrss under sandstorm to choke on, for example, JWZ's feed:
  https://www.jwz.org/blog/feed/

Traced it as far as relating to ttrss-under-sandstorm using sandstorm-httpGet, and JWZ's "403 Bots Forbidden" logic.
