### ISSUE TITLE
node-capnp/capnp-test.js fails

### ISSUE THREAD

**Issue by dwrensha** [sandstorm-io/sandstorm#207]
```
jstest: node-capnp/capnp-test.js
  full log: tmp/node-capnp/capnp-test.js.log
Makefile:132: recipe for target 'tmp/.ekam-run' failed
make: *** [tmp/.ekam-run] Error 1
$ cat tmp/node-capnp/capnp
cat: tmp/node-capnp/capnp: No such file or directory
$ cat tmp/node-capnp/capnp-test.js.log 

module.js:340
    throw err;
          ^
Error: Cannot find module 'es6-promise'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/david/src/sandstorm/node-capnp/capnp.js:48:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by dwrensha** [comment]
oh, wait. Maybe it's fine. I just tried building without doing the deps symlink thing, and it worked...

**Comment by dwrensha** [comment]
Ah, indeed. My node-capnp was out of date.

**Comment by kentonv** [comment]
This is actually my fault. I had failed to add some files to a commit and pushed it. I later fixed it.
