### ISSUE TITLE
Resumable sessions seemingly not working

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2071]
quoth @zeigerpuppy at <https://github.com/RocketChat/Rocket.Chat/issues/3055#issuecomment-225059991>:

I am having the same problem with Rocket.chat in Sandstorm.

After a period of inactivity, Rocket asks me to log in from the right corner. Closing the grain and reopening it fixes the issue.

log in Sandstorm shows:

```
Error: Requested session that no longer exists, and timed out waiting for client to restore it. This can happen if you have opened an app's content in a new window and then closed it in the UI. If you see this error *inside* the Sandstorm UI, please report a bug and describe the circumstances of the error. [504]
    at server/proxy.js:580:24
    at [object Object]._.extend.withValue (packages/meteor.js:1100:17)
    at packages/meteor.js:445:45
    at runWithEnvironment (package
```

**Comment by kentonv** [comment]
Possibly fixed last week?

**Comment by kiwano** [comment]
My problems in rocketchat bug #3055 are still happening, so that's either a separate bug, or it's unfixed :P

**Comment by kentonv** [comment]
@kiwano The problems you describe in that thread seem to be different. I'll comment there.

**Comment by kentonv** [comment]
@kiwano I opened a separate bug: https://github.com/sandstorm-io/meteor-accounts-sandstorm/issues/27

**Comment by kiwano** [comment]
Much thanks; I'll deal with the new bug now...
