### ISSUE TITLE
Match Failed [400]

### ISSUE THREAD

**Issue by ItsDaGeek** [sandstorm-io/sandstorm#2229]
I am getting an error when I am trying to edit any field in the Admin / Personalization menu. More specifically, "Match Failed [400]".

Here is a segment of the log when invoked:
```
Exception while invoking method 'setPersonalizationSettings' Error: Match error: Missing key 'termsOfServiceUrl'
    at exports.check (packages/check/match.js:34:1)
    at [object Object].setPersonalizationSettings (server/admin/personalization-server.js:16:5)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1704:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:707:46
    at tryCallTwo (/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:200:13)
Sanitized and reported to the client as: Match failed [400]

```

Thank you for your help.

EDIT: I tested it in multiple DigitalOcean Environments, same result.

**Comment by dwrensha** [comment]
I was able to reproduce this problem on a fresh install. As a workaround, you should be able to get it succeed by supplying a value to every one of the fields.
