### ISSUE TITLE
ENOTSOCK error in listen(), resulting in Sandstorm failing to start

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2355]
(Reported originally by @JonTheNiceGuy via IRC today using this pastebin: http://pastebin.com/2b16YhLs )

Seemingly, steps to reproduce:

- Have sandcats HTTPS enabled

- Start Sandstorm

Expected behavior:

- Sandstorm successfully starts listening on HTTPS

Actual behavior, seemingly:

- Sandstorm goes into a restart loop

**Comment by paulproteus** [comment]
Context: The crash occurs on line 428 of `meteor-bundle-main.js`, which is:

```            oldListen.call(server, {fd: 4}, cb);```

I wonder:

- why fd 4 isn't a socket on Jon's machine
- if that's true on other people's machines
- if there's a better behavior we should do when this happens

**Comment by paulproteus** [comment]
Having difficulty reproducing this so far. Thing I've tried so far:

```
sudo service sandstorm stop
sudo nc -l -p 443 &
sudo service sandstorm start
```

But this provides different log spam:

```
sandstorm/util.c++:929: fatal: *exception = sandstorm/run-bundle.c++:1876: failed: bind(sockFd, reinterpret_cast<sockaddr *>(&sa), sizeof(sockaddr_in)): Address already in use
stack: 0x4dbb32 0x4dbada 0x45507e
** Front-end died immediately after starting.
** Sleeping for a bit before trying again...
```

not the particular error that Jon is getting.

**Comment by paulproteus** [comment]
To figure this out, perhaps @JonTheNiceGuy you can provide the output of

```
sudo ls -l /proc/$(pgrep --full sandstorm-main.js --newest)/fd
```

For me, that output is:

```
$ sudo ls -l /proc/$(pgrep --full sandstorm-main.js --newest)/fd
total 0
lr-x------ 1 sandstorm sandstorm 64 Aug  9 16:10 0 -> /dev/null
l-wx------ 1 sandstorm sandstorm 64 Aug  9 16:10 1 -> /opt/sandstorm/var/log/sandstorm.log
l-wx------ 1 sandstorm sandstorm 64 Aug  9 16:10 10 -> pipe:[71710675]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 11 -> anon_inode:[eventfd]
lr-x------ 1 sandstorm sandstorm 64 Aug  9 16:10 12 -> /
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 13 -> socket:[71710795]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 14 -> socket:[71710797]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 15 -> socket:[71710799]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 16 -> socket:[71710801]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 17 -> socket:[71710803]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 18 -> socket:[71710805]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 19 -> socket:[71710807]
l-wx------ 1 sandstorm sandstorm 64 Aug  9 16:10 2 -> /opt/sandstorm/var/log/sandstorm.log
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 20 -> socket:[71710811]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 21 -> socket:[71710813]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 22 -> socket:[71710815]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 23 -> socket:[71710819]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 24 -> socket:[71710821]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 25 -> socket:[71710823]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 26 -> socket:[71710932]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:11 27 -> socket:[71712686]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 3 -> socket:[71710665]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 4 -> socket:[71710666]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 5 -> socket:[71710667]
lr-x------ 1 sandstorm sandstorm 64 Aug  9 16:10 6 -> pipe:[71710674]
l-wx------ 1 sandstorm sandstorm 64 Aug  9 16:10 7 -> pipe:[71710674]
lrwx------ 1 sandstorm sandstorm 64 Aug  9 16:10 8 -> anon_inode:[eventpoll]
lr-x------ 1 sandstorm sandstorm 64 Aug  9 16:10 9 -> pipe:[71710675]
```

**Comment by JonTheNiceGuy** [comment]
http://jonspriggs.plus.com/proc.txt
http://jonspriggs.plus.com/ps.txt
http://jonspriggs.plus.com/netstat.txt

**Comment by inkybutton** [comment]
Hi @paulproteus , I think I ran into the same problem. I had a working server using a sandcats.io domain. But then I set up sniproxy to share my server's 443 port with Apache, adjusted sandstorm.conf accordingly, and have been unable to start up the server.

Any help would be appreciated!
Noel.

Error says:
Error: listen ENOTSOCK
    at Object.exports._errnoException (util.js:907:11)
    at exports._exceptionWithHostPort (util.js:930:20)
    at Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Server.listen (net.js:1350:7)
    at listenIfKey (/sandstorm-main.js:443:23)
 
Line 443 in my sandstorm-main.js is:  `oldListen.call(server, {fd: 4}, cb);`

Here's output you asked for:
// When sandstorm.log says Sandstorm is doing things
$ sudo ls -l /proc/$(pgrep --full sandstorm-main.js --newest)/fd
total 0
lr-x------ 1 sandstorm sandstorm 64 Sep 27 00:12 0 -> /dev/null
l-wx------ 1 sandstorm sandstorm 64 Sep 27 00:12 1 -> /opt/sandstorm/var/log/sandstorm.log
l-wx------ 1 sandstorm sandstorm 64 Sep 27 00:12 2 -> /opt/sandstorm/var/log/sandstorm.log
lrwx------ 1 sandstorm sandstorm 64 Sep 27 00:12 3 -> socket:[2926941]
lr-x------ 1 sandstorm sandstorm 64 Sep 27 00:12 4 -> pipe:[2928829]
l-wx------ 1 sandstorm sandstorm 64 Sep 27 00:12 5 -> pipe:[2928829]
lrwx------ 1 sandstorm sandstorm 64 Sep 27 00:12 6 -> anon_inode:[eventpoll]
lr-x------ 1 sandstorm sandstorm 64 Sep 27 00:12 7 -> pipe:[2928830]
l-wx------ 1 sandstorm sandstorm 64 Sep 27 00:12 8 -> pipe:[2928830]
lrwx------ 1 sandstorm sandstorm 64 Sep 27 00:12 9 -> anon_inode:[eventfd]

// When sandstorm.log says "** Sleeping for a bit before trying again..."
$ sudo ls -l /proc/$(pgrep --full sandstorm-main.js --newest)/fd
ls: cannot access /proc//fd: No such file or directory

**Comment by paulproteus** [comment]
Hi @inkybutton ! Thanks for filing this.

I'm about to go on vacation, so I'll tag @jparyani and @kentonv to see if they can possibly help get to the bottom of this. Some other stuff that would be useful to us in finding out what's going on would be:

- Contents of /opt/sandstorm/sandstorm.conf

- Output of `sudo lsof -i TCP -n -sTCP:LISTEN` to see what other processes are listening on global ports

It could be the case that seeing an strace of Sandstorm startup would be useful, too. I'll refrain from asking for that right now because I haven't tested the best way to ask for it.

Let me know! Thanks so much; I hope we can get to the bottom of this, because the last thing I want is people's servers to be broken!

**Comment by inkybutton** [comment]
Hey, I managed to get around it! I commented out PORT in sandstorm.conf because I thought I only needed to specify HTTPS_PORT for an encrypted connection. I have now uncommented it and the server starts successfully. Let me know if this is expected behaviour? I certainly think a clearer error would be better.

**Comment by pgrm** [comment]
A missing configuration for `PORT` was also my problem
