### ISSUE TITLE
Sometimes not updating to server (etherpad) multiple editor/authors ... (shared access)

### ISSUE THREAD

**Issue by melissabutterfly321** [sandstorm-io/sandstorm#2367]
Sometimes its not updating the etherpad if my friend is saving information and i am same time.
Mine gets saved his does not.

I did noticec he had some script error ... which he just clicked 'stop script' on.

I told him never edit if he gets the error instead keep refreshing until the error doesn't pop up.

Is this the problem or something else ? 

Sometimes can't click and edit the text.

Sometimes friend will change color to text but it wont change all the sudden.
But i noticed just 30 seconds ago any changes he makes i see in real time. He changes
text color it doesn't change. And no more changes he makes are being recorded.
He needs to RELOAD the app. 

2016-08-11 09:46:13.562] [WARN] client - too much recursion -- { errorId: 'wwPiEdTZnEdaKp2HY6OQ',
  msg: 'too much recursion',
  url: 'https://1ff1d3538430c1718f0a6911cc92e1f1.
  linenumber: 71,
  userAgent: 'Mozilla/5.0 (X11; FreeBSD amd64; rv:42.0) Gecko/20100101 Firefox/42.0' }
[2016-08-11 09:46:13.647] [INFO] ueberDB - Flushed 1 values
[2016-08-11 09:46:13.785] [WARN] client - too much recursion -- { errorId: 'EojrN2UEvdTG5A3JeEPV',
  msg: 'too much recursion',
  url: 'https://1ff1d3538430c1718f0a6911cc92e1f1.
  linenumber: 72,
  userAgent: 'Mozilla/5.0 (X11; FreeBSD amd64; rv:42.0) Gecko/20100101 Firefox/42.0' }
[2016-08-11 09:46:13.852] [INFO] ueberDB - Flushed 1 values
[2016-08-11 09:46:16.468] [WARN] console - Error: Can't apply USER_CHANGES Z:ae8>2w|7b=39l*1|3+3*1*q*k+9*1|1+1*1*q*k+l*1|1+1*1*q*k+h*1|1+1*1*q*k+1e*1|1+1$

 Email: -
Home address:
 with oldLen 13472 to document of length 13697
    at /src/node/handler/PadMessageHandler.js:784:25
    at /src/node_modules/async/lib/async.js:610:21
    at /src/node_modules/async/lib/async.js:249:17
    at iterate (/src/node_modules/async/lib/async.js:149:13)
    at /src/node_modules/async/lib/async.js:160:25
    at /src/node_modules/async/lib/async.js:251:21
    at /src/node_modules/async/lib/async.js:615:34
    at Object.async.whilst (/src/node_modules/async/lib/async.js:686:13)
    at /src/node/handler/PadMessageHandler.js:733:13
    at /src/node_modules/async/lib/async.js:610:21
[2016-08-11 09:46:16.473] [INFO] ueberDB - Flushed 1 values
[2016-08-11 09:46:16.776] [INFO] access - [LEAVE] Pad "main": Author "a.67TG39X8gki1Mtey" on client o40KicTSGmZ5kkLkAAAO with IP "127.0.0.1" left the pad
[2016-08-11 09:46:37.211] [INFO] client - DIAGNOSTIC-INFO: {"disconnectedMessage":"reconnect_timeout","padId":"main","socket":{}}
[2016-08-11 09:46:37.218] [INFO] ueberDB - Flushed 1 values
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
[2016-08-11 09:48:40.656] [INFO] ueberDB - Flushed 3 values
[2016-08-11 09:48:41.665] [INFO] ueberDB - Flushed 3 values
[2016-08-11 09:48:44.790] [INFO] ueberDB - Flushed 3 values

**Comment by melissabutterfly321** [comment]
Please help need this fixed ASAP.

**Comment by kentonv** [comment]
@melissabutterfly321 My guess is that this is a side effect of your server not having enough RAM, as you reported in other issues. Possibly, one or more processes on the serving path are being killed or are being suspended for long periods of time while the machine swaps, and this delays the communications between you and your friend.

I'm going to close this issue since it seems like it's due to insufficient RAM, but let me know if you continue to see problems after adding more RAM.
