### ISSUE TITLE
LDAP verified fetching seems to fail with a crash

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandstorm#2533]
![screenshot](https://cloud.githubusercontent.com/assets/25457/18452972/e2d8d544-78f1-11e6-8d37-efe93a4f334a.png)

```
Exception when trying to renew feature key: TypeError: Cannot read property 'settings' of undefined
    at SandstormDb.getLdapEmailField (packages/sandstorm-db/db.js:1495:21)
    at Function.SandstormDb.getVerifiedEmails (packages/sandstorm-db/profile.js:266:73)
    at packages/sandstorm-db/profile.js:336:19
    at Array.forEach (native)
    at Function.SandstormDb.getUserEmails (packages/sandstorm-db/profile.js:333:15)
    at server/feature-key.js:263:45
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1057:16)
    at Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:904:44)
    at server/feature-key.js:262:42
    at reportRenewalProblem (server/feature-key.js:240:29)
```

**Comment by paulproteus** [comment]
I'm assigning this to Drew for now; Drew, feel free to assign to someone else.

**Comment by paulproteus** [comment]
FWIW I don't know for sure if this means LDAP login is broken.

**Comment by zarvox** [comment]
LDAP login is not itself broken, but getting email addresses from of LDAP users is broken.
