### ISSUE TITLE
LDAPS with self-signed certificate crash front-end

### ISSUE THREAD

**Issue by Alex131089** [sandstorm-io/sandstorm#2592]
All in the title.

Error in logs : 
```
** Front-end died! Restarting it...
Migrations already applied: 31/31
Exception while invoking method 'login' TypeError: Cannot read property 'on' of undefined
    at setupSocket (/programs/server/npm/node_modules/ldapjs/lib/client/client.js:111:14)
    at Client._connect (/programs/server/npm/node_modules/ldapjs/lib/client/client.js:742:3)
    at new Client (/programs/server/npm/node_modules/ldapjs/lib/client/client.js:247:22)
    at Object.createClient (/programs/server/npm/node_modules/ldapjs/lib/client/index.js:60:12)
    at imports/server/accounts/ldap.js:76:23
    at LDAP.ldapCheck (imports/server/accounts/ldap.js:48:49)
    at [object Object].<anonymous> (server/accounts/ldap/ldap-server.js:25:30)
    at packages/accounts-base/accounts_server.js:471:32
    at tryLoginMethod (packages/accounts-base/accounts_server.js:248:14)
    at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:468:18)
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: self signed certificate in certificate chain
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1022:38)
    at emitNone (events.js:67:13)
    at TLSSocket.emit (events.js:166:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:586:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:428:38)
** Front-end died! Restarting it...
```

**Comment by kentonv** [comment]
@jparyani Can you look at this for Friday-Blurday? Hopefully it's an easy fix!
