### ISSUE TITLE
Rocket.Chat grain stopped working because of Slack bridge extension. Please fix.

### ISSUE THREAD

**Issue by keypair** [sandstorm-io/sandstorm#2815]
Attaching the log...

...
Loaded hubot-help/src/help.coffee
Loaded hello.coffee
Loaded zen.coffee
Exception in callback of async function: Error: getaddrinfo ENOTFOUND slack.com slack.com:443
  at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
  at Object.call (packages/meteor.js:213:24)
  at Object.HTTP.get (/programs/server/packages/http.js:77:20)
  at SlackBridge.populateChannelMap (/programs/server/packages/rocketchat_slackbridge.js:1275:24)
  at /programs/server/packages/rocketchat_slackbridge.js:200:13
  at Function.time (/programs/server/profile.js:301:28)
  at /programs/server/boot.js:304:13
  at /programs/server/boot.js:345:5
  at Function.run (/programs/server/profile.js:480:12)
  at /programs/server/boot.js:343:11
 
    - - - - -
  at errnoException (dns.js:27:10)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
 
[Wed Jan 04 2017 18:35:04 GMT+0000 (UTC)] ERROR Error: getaddrinfo ENOTFOUND slack.com slack.com:443
  at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
  at Object.call (packages/meteor.js:213:24)
  at Object.HTTP.get (/programs/server/packages/http.js:77:20)
  at SlackBridge.populateChannelMap (/programs/server/packages/rocketchat_slackbridge.js:1275:24)
  at /programs/server/packages/rocketchat_slackbridge.js:200:13
  at Function.time (/programs/server/profile.js:301:28)
  at /programs/server/boot.js:304:13
  at /programs/server/boot.js:345:5
  at Function.run (/programs/server/profile.js:480:12)
  at /programs/server/boot.js:343:11
 
    - - - - -
  at errnoException (dns.js:27:10)
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
 
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
info: unable to RTM start, attempting reconnect: Error: getaddrinfo ENOTFOUND slack.com slack.com:443
info: unable to RTM start, attempting reconnect: Error: Unable to process request, received bad null error
info: unable to RTM start, attempting reconnect: Error: getaddrinfo ENOTFOUND slack.com slack.com:443
info: unable to RTM start, attempting reconnect: Error: Unable to process request, received bad null error
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.

**Comment by kentonv** [comment]
Ouch.

Unfortunately, this is a bug in Rocket.Chat, not in Sandstorm. They are the only ones who can fix it.

I have filed a bug against Rocket.Chat: https://github.com/RocketChat/Rocket.Chat/issues/5426

**Comment by engelgabriel** [comment]
Sorry guys, we will fix this asap.
