### ISSUE TITLE
errors log

### ISSUE THREAD

**Issue by bluenevus** [sandstorm-io/sandstorm#2817]
...realloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 5706
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
Migrations already applied: 31/31
Error: Host "sandstorm-www.cai.xskcl.cn" must have exactly one TXT record.
    at server/pre-meteor.js:740:16
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:216:10)
Error: Host "sandstorm-www.cai.xskcl.cn" must have exactly one TXT record.
    at server/pre-meteor.js:740:16
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:216:10)
{"line":"398","file":"oauth_server.js","message":"Error in OAuth Server: redirectUrl (http://apps.microhealthllc.com/) is not on the same host as the app (https://apps.microhealthllc.com/)","time":{"$date":1481128598993},"level":"warn"}
Downloading app: https://app-index.sandstorm.io/packages/a27816e4d76bf4f8593193f52de73cfe
App ready: a27816e4d76bf4f8593193f52de73cfe
fetching keybase 5C5580353165D42FD89E1371A9FF0AD7DEE40258
Error: Error looking up DNS TXT records for host "www.sdosky.com": queryTxt ESERVFAIL sandstorm-www.www.sdosky.com
    at server/pre-meteor.js:716:23
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:214:10)
Error: Error looking up DNS TXT records for host "www.x6cssf.com": queryTxt ESERVFAIL sandstorm-www.www.x6cssf.com
    at server/pre-meteor.js:716:23
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:214:10)
** Restarting to apply update
** Shutting down due to signal
** Starting back-end...
** Starting MongoDB...
note: noprealloc may hurt performance in many applications
about to fork child process, waiting until server is ready for connections.
forked process: 7968
child process started successfully, parent exiting
** Back-end and Mongo started; now starting front-end...
Migrations already applied: 31/31
Error: Error looking up DNS TXT records for host "www.x6cssf.com": queryTxt ESERVFAIL sandstorm-www.www.x6cssf.com
    at server/pre-meteor.js:716:23
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:214:10)
Error: Error looking up DNS TXT records for host "www.x6cssf.com": queryTxt ESERVFAIL sandstorm-www.www.x6cssf.com
    at server/pre-meteor.js:716:23
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:214:10)
Error: Error looking up DNS TXT records for host "www.x6cssf.com": queryTxt ESERVFAIL sandstorm-www.www.x6cssf.com
    at server/pre-meteor.js:716:23
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:214:10)
Downloading app: https://app-index.sandstorm.io/packages/5492a5877c09436dfb43a1ff9635e5dd
App ready: 5492a5877c09436dfb43a1ff9635e5dd
fetching keybase 5C5580353165D42FD89E1371A9FF0AD7DEE40258
Error: Error looking up DNS TXT records for host "cc.xx7p.com": queryTxt ESERVFAIL sandstorm-www.cc.xx7p.com
    at server/pre-meteor.js:716:23
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:214:10)
Downloading app: https://app-index.sandstorm.io/packages/f53e839658cba5d1783670890eeb8352
App ready: f53e839658cba5d1783670890eeb8352
fetching keybase FEB7F40B2344F1C231FD1FACA6990E4676D502DD
Error: Error looking up DNS TXT records for host "www.zxcl12530.cn": queryTxt ESERVFAIL sandstorm-www.www.zxcl12530.cn
    at server/pre-meteor.js:716:23
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:214:10)
Error: Error looking up DNS TXT records for host "www.zxcl12530.cn": queryTxt ESERVFAIL sandstorm-www.www.zxcl12530.cn
    at server/pre-meteor.js:716:23
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:214:10)
Error: Host "sandstorm-www.323.op3ngate033.appspot.com" must have exactly one TXT record.
    at server/pre-meteor.js:740:16
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:216:10)
Error: Host "sandstorm-www.323.op3ngate033.appspot.com" must have exactly one TXT record.
    at server/pre-meteor.js:740:16
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:216:10)
Error: Host "sandstorm-www.z-h-e-n-118.appspot.com" must have exactly one TXT record.
    at server/pre-meteor.js:740:16
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:216:10)
Error: Host "sandstorm-www.z-h-e-n-118.appspot.com" must have exactly one TXT record.
    at server/pre-meteor.js:740:16
    at QueryReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:216:10)

**Comment by bluenevus** [comment]
Interesting.  I’m able to authenticate using oath with google…still logs me in

--
Vr, Frank

**Comment by kentonv** [comment]
Hmm, well if it's working, great. Not sure why the error message, then.

Is there anything else in the log you're concerned about, or should we close this issue?

**Comment by bluenevus** [comment]
No concerns.  Just wanted to inform you

--
Vr, Frank

**Comment by kentonv** [comment]
Thanks for the info!
