### ISSUE TITLE
yandex smtp not working

### ISSUE THREAD

**Issue by 001101** [sandstorm-io/sandstorm#2876]
hi,

i really need this nice piece of software, but it just not working with yandex smtp pdd (for domains), so is this confirmed?

thanks in advice

-------------
**log on testmail**

_Error while trying to send test email: {"code":"EAUTH","response":"502 5.5.2 Syntax error, command unrecognized.","responseCode":502,"command":"AUTH PLAIN"} [other-email-sending-error]_

-------------
**@/opt/sandstorm/var/log/sandstorm.log**
(but i can not really confirm this is from now, because there are no timestamps, which should definitely be extended. anyway, I just tried yandex smtp with this instance)

Exception while invoking method 'createAndEmailTokenForUser' Error: Connection timeout
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at smtpSend (imports/server/email.js:78:44)
    at rawSend (imports/server/email.js:87:5)
    at send (imports/server/email.js:176:3)
    at sendTokenEmail (server/accounts/email-token/token-server.js:207:3)
    at _createAndEmailTokenForUser (server/accounts/email-token/token-server.js:274:3)
    at [object Object].createAndEmailTokenForUser (server/accounts/email-token/token-server.js:296:18)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1712:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    - - - - -
    at SMTPConnection._formatError (/programs/server/npm/node_modules/smtp-connection/lib/smtp-connection.js:528:15)
    at SMTPConnection._onError (/programs/server/npm/node_modules/smtp-connection/lib/smtp-connection.js:514:16)
    at SMTPConnection.<anonymous> (/programs/server/npm/node_modules/smtp-connection/lib/smtp-connection.js:236:14)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by 001101** [comment]
can be closed, i did used mx.yandex.net instead of smtp.yandex.com, works now :)

**Comment by kentonv** [comment]
Glad you got it working!

**Comment by 001101** [comment]
not really, email works, but service is not usable.
