### ISSUE TITLE
Sandstorm failed to start after auto-upgrade

### ISSUE THREAD

**Issue by GitHubGeek** [sandstorm-io/sandstorm#2942]
My sandstorm instance ran into "boot loop" after auto-upgraded to release 208. Logs:

```
capnp/rpc.c++:142: info: returning failure over rpc; exception = sandstorm/backend.c++:44: failed: rename(path, tmpPath): Permission denied; path = /var/sandstorm/apps/a3024432ac3868b1765de660e6c1ec7c; tmpPath = /var/sandstorm/tmp/deleting.1496118904.133
stack: 0x5d524e 0x5cf3d3 0x5cf49b 0x62d700 0x4fb712 0x553140
/programs/server/node_modules/fibers/future.js:313
                                                throw(ex);
                                                ^

Error: remote exception: rename(path, tmpPath): Permission denied; path = /var/sandstorm/apps/a3024432ac3868b1765de660e6c1ec7c; tmpPath = /var/sandstorm/tmp/deleting.1496118904.133
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at waitPromise (imports/server/async-helpers.js:39:35)
    at deletePackageInternal (server/installer.js:69:7)
    at [object Object]._.extend.forEach (packages/mongo/mongo_driver.js:1064:16)
    at [object Object].Cursor.(anonymous function) [as forEach] (packages/mongo/mongo_driver.js:911:44)
    at server/installer.js:122:41
    at Function.time (/programs/server/profile.js:309:28)
    at /programs/server/boot.js:312:13
    at /programs/server/boot.js:353:5
    at Function.run (/programs/server/profile.js:510:12)
    - - - - -
    at Error (native)
** Front-end died immediately after starting.
** Sleeping for a bit before trying again...
```

Please show me how to fix this issue. Thank you so much!

**Comment by kentonv** [comment]
Hi,

It seems that somehow the permissions on `/opt/sandstorm/var/sandstorm/apps/a3024432ac3868b1765de660e6c1ec7c` or maybe on `/opt/sandstorm/var/sandstorm/apps` were set such that Sandstorm can't delete them. These locations should be writable by the `sandstorm` user. If you correct the ownership / permissions then Sandstorm should be able to run again.

**Comment by ocdtrekkie** [comment]
I'm going to close this one for lack of response.
