### ISSUE TITLE
Error: Requested session that no longer exists, and timed out waiting for client to restore it. 

### ISSUE THREAD

**Issue by hiromipaw** [sandstorm-io/sandstorm#2956]
We run a sandstorm instance and we are seeing the following error lately:

```
Error: Requested session that no longer exists, and timed out waiting for client to restore it. This can happen if you have opened an app's content in a new window and then closed it in the UI. If you see this error *inside* the Sandstorm UI, please report a bug and describe the circumstances of the error. [504]
    at server/proxy.js:617:24
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/meteor.js:445:45
    at runWithEnvironment (packages/meteor.js:1176:24)
```

Please note that this issue is happening after a VM reboot, shall we assume this is expected behaviour?

Thanks for your help.

**Comment by kentonv** [comment]
I suspect that whatever is causing #2957 is also causing this problem...

**Comment by kentonv** [comment]
I believe this was fixed. Let me know if not.
