### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by ertanalytics** [sandstorm-io/sandstorm#2962]
When attempting to restore a backed up grain, I get permission denied.  I am hosting on Ubuntu with a backed up copy of my environment from another machine following the guide: https://docs.sandstorm.io/en/latest/administering/backups/ 

Upload failed: 500 Internal Server Error

Error: remote exception: open(name.cStr(), flags, mode): Permission denied; name = /var/sandstorm/backups/Ro6v6guepZsTyDrR3.uploading
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at waitPromise (imports/server/async-helpers.js:39:35)
    at [object Object].route.action (server/backup.js:263:11)
    at boundNext (packages/iron_middleware-stack.js:408:31)
    at runWithEnvironment (packages/meteor.js:1180:24)
    at packages/meteor.js:1193:14
    at [object Object].urlencodedParser (/programs/server/npm/node_modules/meteor/iron_router/node_modules/body-parser/lib/types/urlencoded.js:91:37)
    at packages/iron_router.js:886:36
    at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
    at [object Object].hookWithOptions (packages/iron_router.js:885:27)
    - - - - -
    at Error (native)

![image](https://user-images.githubusercontent.com/7130518/28343851-01119320-6be5-11e7-908c-61771dcfd1a5.png)

**Comment by zenhack** [comment]
I would verify that the permissions for all of /opt/sandstorm are correct -- it looks like sandstorm is being denied access to some file. The file name in question should be at the end of that top line, but it's cut off in the screenshot.

**Comment by zenhack** [comment]
Ack, I see that you also pasted the text. Make sure that the sandstorm user can write to /opt/sandstorm/var/sandstorm/backups.

**Comment by ertanalytics** [comment]
Hi Zenhack, thanks for your input.  I ran this command based on your input and the upload error is no longer appearing.

`sudo chown sandstorm: /opt/sandstorm/var/sandstorm/backups`

I am still seeing other errors after uploading, however I have other tickets open on those issues.

Thanks again!

**Comment by zenhack** [comment]
You're welcome.
