### ISSUE TITLE
Restoring Backed Up Grain - Peer Disconnected Error

### ISSUE THREAD

**Issue by ertanalytics** [sandstorm-io/sandstorm#2963]
Decided to try to get a backup system setup on another machine and before I did that I went ahead and backed up all of my grains.  At some point in this effort my initial system started to fail and sandstorm would not start due to a mongod error that created no logs.  I have since created the backup environment and reinstalled on the original environment, but grains that did not have users granted access to them with edit privileges are returning the following error:

Error: remote exception: Peer disconnected.
    at Error (native)
C++ location:(remote):??
type: disconnected

![image](https://user-images.githubusercontent.com/7130518/28347946-cdeed2da-6bff-11e7-9e15-7b789664fe7e.png)

**Comment by zenhack** [comment]
Same thing, can you share the contents of tge grain log? (Monitor icon)

**Comment by ertanalytics** [comment]
...** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2017-07-19T19:47:58.335+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 6
ERROR: child process failed, exited with error number 14
Mongo exited with error code: 14
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2017-07-19T19:47:58.736+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 6
ERROR: child process failed, exited with error number 14
Mongo exited with error code: 14
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns

**Comment by ertanalytics** [comment]
Wekan is the grain app.

> 

Admin/System Log
capnp/rpc.c++:142: info: returning failure over rpc; exception = kj/async-io.c++:34: failed: expected result >= minBytes; Premature EOF
stack: 0x4f7fc2 0x5df650 0x5dfcb0 0x5e02e0 0x5ddab0 0x5e1e70 0x5560c0
> 

Then Shortly Afterwards:

> 

Exception while invoking method 'keepSessionAlive' Error: remote exception: expected result >= minBytes; Premature EOF
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at waitPromise (imports/server/async-helpers.js:39:35)
    at [object Object].Meteor.methods.keepSessionAlive (server/proxy.js:491:9)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1768:12)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
    at packages/ddp-server/livedata_server.js:717:46
    at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    - - - - -
    at Error (native)

> 

And the Mongo.log:

> 
2017-07-19T20:45:46.341+0000 [clientcursormon] mem (MB) res:52 virt:755
2017-07-19T20:45:46.341+0000 [clientcursormon]  mapped (incl journal view):256
2017-07-19T20:45:46.342+0000 [clientcursormon]  connections:6
2017-07-19T20:45:46.342+0000 [clientcursormon]  replication threads:32
2017-07-19T20:50:46.380+0000 [clientcursormon] mem (MB) res:51 virt:755
2017-07-19T20:50:46.380+0000 [clientcursormon]  mapped (incl journal view):256
2017-07-19T20:50:46.380+0000 [clientcursormon]  connections:6
2017-07-19T20:50:46.380+0000 [clientcursormon]  replication threads:32
2017-07-19T20:55:46.418+0000 [clientcursormon] mem (MB) res:50 virt:755
2017-07-19T20:55:46.418+0000 [clientcursormon]  mapped (incl journal view):256
2017-07-19T20:55:46.418+0000 [clientcursormon]  connections:6
2017-07-19T20:55:46.418+0000 [clientcursormon]  replication threads:32

>

**Comment by ertanalytics** [comment]
I did a new install with the "curl https://install.sandstorm.io | bash" command and basically followed these steps to reinstall on one of my machines to determine the default permissions:

> 

Reinstall sandstorm on Ubuntu 16.04

~$ sudo sandstorm uninstall
~$ sudo userdel sandstorm
~$ sudo rm -r /opt/
~$ sudo service nginx stop
~$ curl https://install.sandstorm.io | bash

ENTER ENTER [RANDOM CHARS] ENTER [EMAIL ADDRESS]

Should provide a URL like: https://ertasdfs.sandcats.io/setup/token/b7a7706e1d5084a

:~$ sudo reboot

-------
Reopen Console and SSH back into the machine
-------

:~$ sudo nano /opt/sandstorm/sandstorm.conf
-------
Edit to match:

SERVER_USER=sandstorm
PORT=6080
MONGO_PORT=6081
BIND_IP=0.0.0.0
BASE_URL=https://websitehere.us
WILDCARD_HOST=*.websitehere.us
UPDATE_CHANNEL=dev
ALLOW_DEV_ACCOUNTS=false
SMTP_LISTEN_PORT=30025
-------

:~$ sudo reboot

-------
Reopen Console and SSH back into the machine
-------

:~$ sudo sandstorm admin-token


Visit the new URL

> 

I copied over the permissions and the permission set in the issue:  'Upload Error #2962' appears to have been reversed and subsequently failed to upload.

During this process I also noticed the permission changes to the defaults based on the above install process appeared to force an automatic logout after an email based token login only seconds after putting in the token and logging in.  These seconds before it forced me out I was able to access anything as normal, but it soon kicked me off.  To 'resolve' this I created another admin-token and went through the setup and somehow this stopped it from kicking me off.

Now I get a new error:

Upload failed: 500 Internal Server Error
Error: connect(): Connection refused
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at waitPromise (imports/server/async-helpers.js:39:35)
    at [object Object].route.action (server/backup.js:263:11)
    at boundNext (packages/iron_middleware-stack.js:408:31)
    at runWithEnvironment (packages/meteor.js:1180:24)
    at packages/meteor.js:1193:14
    at [object Object].urlencodedParser (/programs/server/npm/node_modules/meteor/iron_router/node_modules/body-parser/lib/types/urlencoded.js:91:37)
    at packages/iron_router.js:886:36
    at [object Object]._.extend.withValue (packages/meteor.js:1126:17)
    at [object Object].hookWithOptions (packages/iron_router.js:885:27)
    - - - - -
    at Error (native)

**Comment by ertanalytics** [comment]
I went through all of the folders and one was even missing.  Adding that back and changing all the permissions seems to have fixed the issue. 

Thanks for taking the time!

**Comment by ertanalytics** [comment]
Sorry - this one is still happening (reopening).  I was able to get one grain to restore, however the other backed up grains will not restore.   

**Error message:**

Error: remote exception: Peer disconnected.
    at Error (native)
C++ location:(remote):??
type: disconnected

![image](https://user-images.githubusercontent.com/7130518/28446507-c4b4baee-6d90-11e7-91bc-8c7f619d3d18.png)


**Mongo.log:**

2017-07-21T02:10:42.862+0000 [clientcursormon] mem (MB) res:49 virt:757
2017-07-21T02:10:42.862+0000 [clientcursormon]  mapped (incl journal view):256
2017-07-21T02:10:42.862+0000 [clientcursormon]  connections:6
2017-07-21T02:10:42.862+0000 [clientcursormon]  replication threads:32
2017-07-21T02:13:42.885+0000 [clientcursormon] mem (MB) res:54 virt:757
2017-07-21T02:13:42.885+0000 [clientcursormon]  mapped (incl journal view):256
2017-07-21T02:13:42.885+0000 [clientcursormon]  connections:6
2017-07-21T02:13:42.885+0000 [clientcursormon]  replication threads:32

**Debug Log:**

...-21T02:09:15.200+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 6
child process started successfully, parent exiting
** Starting Meteor...
Exception from sub id undefined Error: connection closed
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:986:47)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1020:22)
    at SynchronousCursor.map (packages/mongo/mongo_driver.js:1030:10)
    at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1054:17)
    at Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:869:44)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:23:1)
    at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
    at [object Object].update (packages/mongo/collection.js:589:29)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:191:1)
    at Subscription.Meteor.methods.setPresence.presences.update._id (packages/3stack_presence/packages/3stack_presence.js:243:1)
    at packages/matb33_collection-hooks/collection-hooks.js:275:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Subscription._handler (packages/matb33_collection-hooks/collection-hooks.js:274:1)
    at packages/check/match.js:107:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    - - - - -
    at [object Object].<anonymous> (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:618:45)
    at [object Object].emit (events.js:92:17)
    at [object Object].<anonymous> (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:171:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:550:12)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:466:12)

/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						      ^
Error: failed to connect to [127.0.0.1:4001]
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at packages/meteor/helpers.js:119:1
    at new FS.StorageAdapter (packages/cfs_storage-adapter/packages/cfs_storage-adapter.js:264:1)
    at new FS.Store.GridFS (packages/cfs_gridfs/packages/cfs_gridfs.js:54:1)
    at meteorInstall.models.attachments.js (models/attachments.js:6:5)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at /programs/server/app/app.js:5184:1
    at /programs/server/boot.js:297:10
    at Array.forEach (native)
    at Function._.each._.forEach (/programs/server/node_modules/underscore/underscore.js:79:11)
    at /programs/server/boot.js:133:5
    - - - - -
    at [object Object].<anonymous> (/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:458:13)
** HTTP-BRIDGE: App server exited with status code: 8
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2017-07-21T02:09:18.384+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 6
child process started successfully, parent exiting
** Starting Meteor...
Exception from sub id undefined Error: connection closed
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at SynchronousCursor._nextObject (packages/mongo/mongo_driver.js:986:47)
    at SynchronousCursor.forEach (packages/mongo/mongo_driver.js:1020:22)
    at SynchronousCursor.map (packages/mongo/mongo_driver.js:1030:10)
    at SynchronousCursor.fetch (packages/mongo/mongo_driver.js:1054:17)
    at Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:869:44)
    at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:23:1)
    at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
    at [object Object].update (packages/mongo/collection.js:589:29)
    at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed_collection2-core/lib/collection2.js:191:1)
    at Subscription.Meteor.methods.setPresence.presences.update._id (packages/3stack_presence/packages/3stack_presence.js:243:1)
    at packages/matb33_collection-hooks/collection-hooks.js:275:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Subscription._handler (packages/matb33_collection-hooks/collection-hooks.js:274:1)
    at packages/check/match.js:107:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    - - - - -
    at [object Object].<anonymous> (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:618:45)
    at [object Object].emit (events.js:92:17)
    at [object Object].<anonymous> (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:171:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:550:12)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:466:12)

/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						      ^
Error: failed to connect to [127.0.0.1:4001]
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:449:15)
    at packages/meteor/helpers.js:119:1
    at new FS.StorageAdapter (packages/cfs_storage-adapter/packages/cfs_storage-adapter.js:264:1)
    at new FS.Store.GridFS (packages/cfs_gridfs/packages/cfs_gridfs.js:54:1)
    at meteorInstall.models.attachments.js (models/attachments.js:6:5)
    at fileEvaluate (packages/modules-runtime/.npm/package/node_modules/install/install.js:153:1)
    at require (packages/modules-runtime/.npm/package/node_modules/install/install.js:82:1)
    at /programs/server/app/app.js:5184:1
    at /programs/server/boot.js:297:10
    at Array.forEach (native)
    at Function._.each._.forEach (/programs/server/node_modules/underscore/underscore.js:79:11)
    at /programs/server/boot.js:133:5
    - - - - -
    at [object Object].<anonymous> (/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/programs/server/npm/node_modules/meteor/cfs_gridfs/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:458:13)
** HTTP-BRIDGE: App server exited with status code: 8
** SANDSTORM SUPERVISOR: App exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
*** lost connection to grain (probably because it shut down) ***

**Comment by zenhack** [comment]
It looks to me like (a) the grain you're using uses mongo as part of it's internal storage (so this is entirely separate fromt he mongo server/database that sandstorm itself is using), and (b) the app running in the grain is unable to connect to its local mongo instance.

One thing that could be happening is that your backups are corrupted somehow. Do you still have the original grains on the other system? If you back up the same grains again do you get the same behavior with the new backups?

**Comment by ertanalytics** [comment]
Thanks again, it seems like I made these backups after I had already changed the permissions.  I was able to restore older backups that were not corrupted by my changes.
