### ISSUE TITLE
Mobile App Websocket can't access with new Gateway

### ISSUE THREAD

**Issue by peterlee0127** [sandstorm-io/sandstorm#3052]
I am using the dev channel of sandstorm v0.228 (2018-03-04)
Start from March 3, we found the mobile app websocket can't access. 
The request web socket uri: 
wss://ey-api-f59b7ef8cbe5e41df453edf9b6c63493.xxxxxxxxx/.sandstorm-token/##############
<img width="1210" alt="out" src="https://user-images.githubusercontent.com/906325/37012484-d8dbd73e-212f-11e8-976b-681d287303f8.png">
It's return 401 Unauthorized.

Before using the new gateway, it works.
We are using the Rocket.Chat App in Sandstorm. It's mobile app using the websocket to contact the Rocket.Chat server(grains).

https://sandstorm.io/news/2018-02-19-http-rewrite-and-more

Log 
```kj/compat/http.c++:3718: error: unhandled exception in HTTP server; exception = kj/async-io-unix.c++:139: disconnected: ::write(fd, buffer, size): Broken pipe
stack: 0x4ea0bc 0x685e86 0x4d6b11 0x6af060 0x6b4ef0
Unhandled exception in Promise:  { Error: remote exception: stream disconnected prematurely cppFile: '(remote)', line: 0, kjType: 'disconnected' }
Unhandled exception in Promise:  { Error: remote exception: stream disconnected prematurely cppFile: '(remote)', line: 0, kjType: 'disconnected' }
Unhandled exception in Promise:  { Error: remote exception: stream disconnected prematurely cppFile: '(remote)', line: 0, kjType: 'disconnected' }
Unhandled exception in Promise:  { Error: remote exception: stream disconnected prematurely cppFile: '(remote)', line: 0, kjType: 'disconnected' }
Error: remote exception: stream disconnected prematurely
 => awaited here:
    at Promise.await (/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at getUiViewAndUserInfo (server/gateway-router.js:212:20)
    at inMeteor (server/gateway-router.js:393:36)
    at inMeteorInternal (imports/server/async-helpers.js:24:17)
    at Meteor.bindEnvironment.callback (imports/server/async-helpers.js:12:3)
    at runWithEnvironment (packages/meteor.js:1240:24)
    at packages/meteor.js:1253:14
    at Promise (imports/server/async-helpers.js:22:5)
    at new Promise (<anonymous>)
    at inMeteor (imports/server/async-helpers.js:21:10)
    at GatewayRouterImpl.openApiSession (server/gateway-router.js:374:12)
    at /node_modules/capnp.js:174:21
    at /programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Unhandled exception in Promise:  { Error: remote exception: stream disconnected prematurely cppFile: '(remote)', line: 0, kjType: 'disconnected' }
```

**Comment by kentonv** [comment]
Oh geez. I totally forgot that .sandstorm-token was a thing. :(

I should be able to fix this tonight. Sorry for the inconvenience and thanks for reporting the issue.

**Comment by kentonv** [comment]
I've pushed a release fixing this. You should receive an update automatically within 24 hours, or do `sudo sandstorm update` on the server to get it immediately.

**Comment by peterlee0127** [comment]
Thanks
