### ISSUE TITLE
Using LDAP with StartTLS

### ISSUE THREAD

**Issue by jetman92** [sandstorm-io/sandstorm#3085]
Hello, I'm trying to use LDAP with StartTLS but I keep getting the following error : 

`Exception while invoking method 'login' { ConfidentialityRequiredError: TLS confidentiality required
    at messageCallback (/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1419:45)
    at Parser.onMessage (/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1089:14)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at Parser.write (/programs/server/npm/node_modules/ldapjs/lib/messages/parser.js:111:8)
    at Socket.onData (/programs/server/npm/node_modules/ldapjs/lib/client/client.js:1076:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20) lde_message: 'TLS confidentiality required', lde_dn: null }`

Does Sandstrom supports StartTLS with LDAP? Or if not, are there any workarounds?

Thanks.

**Comment by xet7** [comment]
Just quessing, maybe use URL similar like at 
https://github.com/wekan/wekan/wiki/Troubleshooting-Mail#starttls-sending-test-email-failed
```
url='smtp://support%40example.com:password@mail.example.com:587/?ignoreTLS=true&tls={rejectUnauthorized:false}&secure=false'
```
