### ISSUE TITLE
remote exception: stream disconnected prematurely

### ISSUE THREAD

**Issue by staticdnweb** [sandstorm-io/sandstorm#3104]
sometime i run app grain error, chrome show: "did't not send any data" status & i found some issue in sandstorm log file. like that:
`remote exception: stream disconnected prematurely:
 => awaited here:
    at Promise.await (/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:60:12)
    at getUiViewAndUserInfo (server/gateway-router.js:212:20)
    at inMeteor (server/gateway-router.js:311:36)
    at inMeteorInternal (imports/server/async-helpers.js:24:17)
    at Meteor.bindEnvironment.callback (imports/server/async-helpers.js:12:3)
    at runWithEnvironment (packages/meteor.js:1356:24)
    at packages/meteor.js:1369:14
    at Promise (imports/server/async-helpers.js:22:5)
    at new Promise (<anonymous>)
    at inMeteor (imports/server/async-helpers.js:21:10)
    at GatewayRouterImpl.openUiSession (server/gateway-router.js:266:12)
    at /node_modules/capnp.js:174:21
    at /programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40

Unhandled exception in Promise:  { Error: remote exception: stream disconnected prematurely cppFile: '(remote)', line: 0, kjType: 'disconnected' }
`
What kind of this error? how i can fix it? thanks

**Comment by louis-ulrich** [comment]
Can confirm this bug. Is there any fix?

**Comment by ocdtrekkie** [comment]
> Can confirm this bug. Is there any fix?

Do you have any details about when you see this? Are there specific apps that cause it?

**Comment by louis-ulrich** [comment]
It's a brand new installed version, it occurs in all apps.
Instead of showing the app it stays empty: 

<img width="1512" height="859" alt="Image" src="https://github.com/user-attachments/assets/f46063da-bdac-4e05-be3f-93fcd8009ab5" />

Looking into the debug console it will show:
`...*** couldn't connect to grain (Error: remote exception: stream disconnected prematurely) ***`

Looking at the frame it embedds correctly: https://ui-aa7877029d5585a2c801be2ab13c4ac8.(mydomain).sandcats.io/_sandstorm-init?sessionid=003e2a412a44ea2299bb70188da2f2a3437ebbe80ae1598d22d080707f2259cd&path=/"

Browser's console debug:
[Error] Failed to load resource: The network connection was disconnected. (ui-aa7877029d5585a2c801be2ab13c4ac8.(mydomain).sandcats.io, line 0)

Opening this URL into a new browser:
Safari cannot open the site„https://ui-aa7877029d5585a2c801be2ab13c4ac8.(mydomain).sandcats.io“ because the server has ended the connection unexpectedly. This may occur, if the server is overloaded. Please wait a few minutes and try again.</p>

According to servers free -h excerpt, it is definitely not because an overload.
You may wanna know the result of curl -v https://ui-aa7877029d5585a2c801be2ab13c4ac8.(mydomain).sandcats.io: 

```
* Host ui-aa7877029d5585a2c801be2ab13c4ac8.(mydomain).sandcats.io:443 was resolved.
* IPv6: (none)
* IPv4: 123.456.789.012 (my IP)
*   Trying 123.456.789.012 (my IP):443...
* Connected to ui-aa7877029d5585a2c801be2ab13c4ac8.(mydomain).sandcats.io (123.456.789.012 (my IP)) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: CN=*.(mydomain).sandcats.io
*  start date: Apr  6 20:08:51 2026 GMT
*  expire date: Jul  5 20:08:50 2026 GMT
*  subjectAltName: host "ui-aa7877029d5585a2c801be2ab13c4ac8.(mydomain).sandcats.io" matched cert's "*.(mydomain).sandcats.io"
*  issuer: C=US; O=Let's Encrypt; CN=R13
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
> GET / HTTP/1.1
> Host: ui-aa7877029d5585a2c801be2ab13c4ac8.(mydomain).sandcats.io
> User-Agent: curl/8.5.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 403 Unauthorized
< Content-Length: 142
< Content-Type: text/plain; charset=UTF-8
< Permissions-Policy: interest-cohort=()
< 
**Unauthorized due to missing cookie. Please make sure cookies
are enabled, and that no settings or extensions are blocking
cookies in iframes.**
* Connection #0 to host ui-aa7877029d5585a2c801be2ab13c4ac8.(mydomain).sandcats.io left intact
```


I also rebuild the (brandnew) server and installed it again. The same mistake still happens. 

EDIT: Error massages are freely translated from German.

**Comment by ocdtrekkie** [comment]
I think if you're looking at the ui- domain from a different browser we might be getting unhelpful information, the UiView does depend on a session-specific cookie set from the browser you launch the grain from.

Do you have any browser extensions that do mess with cookies though you could try exempting?

**Comment by louis-ulrich** [comment]
I tried it using Safari, Firefox and Microsoft Edge on several devices with macOS and Windows. None of the browsers worked, even though they have different error messages. Edge e.g. tells "ui-df1f1100bccf5ec69cf2607a20238334.(mydomain).sandcats.io does not have sent any data".

**Comment by ocdtrekkie** [comment]
Oh, wait. You probably have the AppArmor issue near the bottom of this page: https://docs.sandstorm.io/en/latest/administering/install-troubleshooting/

What version of which distribution is your OS?

**Comment by louis-ulrich** [comment]
That's it! Would it be possible to edit this error message, so it is findable by seach engines or AI? I searched like 5 hours with AI to this but never thought about an user namespace error as the browsers just throw SSL errors.

**Comment by ocdtrekkie** [comment]
Honestly it will probably be easier to fix this so it doesn't happen than fix the error message. ;)

We should either have the installer apply that fix or create an AppArmor profile and use that.

**Comment by louis-ulrich** [comment]
True, thanks a lot for your help!
