### ISSUE TITLE
Cannot create new grain of some large applications on Arch

### ISSUE THREAD

**Issue by xarinatan** [sandstorm-io/sandstorm#3125]
Issue is a clone of https://github.com/wekan/wekan/issues/2200 
Basically what happens is, I create a new Wekan grain and it fails to initialize, as seen below
![peek gif of issue](https://user-images.githubusercontent.com/1271027/53250685-3061a280-36bb-11e9-8c94-9b7f23fa213c.gif)

- Rebooting the VM doesn't fix it. 
- There's enough storage both in the VM and on the hypervisor/host (250/400gb | 8.1/10tb) 
- VM is running Arch and has latest updates and a default official kernel
- I can create some other grains like simplechat and contact otter, but not large ones like Rocket.Chat, Wekan, etc.

Only thing I can think of is that both the VM and the host are running BTRFS for storage, I might move the VM's internal storage to XFS to see if that fixes it.. but I'm not sure if that's the real issue or if there's something I'm missing on my Arch setup or this is a known problem of some kind.

**Comment by xarinatan** [comment]
I moved all the data to XFS (inside the VM, still BTRFS on the host), and it seems to have fixed the issue.
Some grains that I made while testing the issue are still broken (mostly the Wekan ones) but some grains that wouldn't start before are now actually working (e.g the RocketChat ones).
I guess the CoW on top of CoW is causing the issue here? but I didn't expect it to full on stop working and cause corruption.. so I'm still trying to figure out what exactly went on, if anyone has any comments they're very welcome.

**Comment by xarinatan** [comment]
Actually scratch that, it seems pretty random whether it works or not, so it's not fixed. 
So, it is not a CoW on CoW issue. I will continue by reinstalling sandstorm on a fresh Arch server to see if it fixes it. I will keep using XFS.

**Comment by xarinatan** [comment]
Sometimes they actually seem to start after first throwing the MongoDB error.. 
```
...** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: privileged
** Starting Mongo...
2019-02-25T09:53:48.318+0000 I STORAGE  [main] Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...

/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [127.0.0.1:4001] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:4001]
    at Pool.<anonymous> (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:336:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:280:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:187:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: privileged
** Starting Mongo...
2019-02-25T09:53:52.313+0000 I STORAGE  [main] Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 10
child process started successfully, parent exiting
** Starting Meteor...
Presence started serverId=FHZ4s....
```
Could it also be caused by timeouts? The server is running on harddisks, but 8 of them in RAID10 with next to zero load so it shouldn't be slow, rebooting the whole VM takes less than 20 seconds..

**Comment by xet7** [comment]
Error is about Node not being able to connect yet to MongoDB, because MongoDB has not started yet.

I do run Wekan on SSD or NVME. There is big difference between harddisk and SSD speed.

**Comment by xarinatan** [comment]
It seems with XFS the performance increase is significant enough that now new large grains load pretty much without a hitch, however I still see the 'MongoError' getting spammed a lot, I wonder if that's a known issue, although the grains don't actually shut down anymore like they previously did.
