### ISSUE TITLE
tests/appHooks fails often

### ISSUE THREAD

**Issue by zarvox** [sandstorm-io/sandstorm#3353]
We've seen tests/appHooks failing frequently (though occasionally, it will flakily pass).

An example failure log: (from https://github.com/sandstorm-io/sandstorm/runs/716159254 )

```
 ✖ tests/appHooks

   - Test saving and restoring capabilities via AppHooks (27.46s)
   Testing if element <.grainlog-contents > pre> contains text: "Running callback: someObjectId".  - expected "Running callback: someObjectId" but got: "...** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
   ** Starting Mongo...
   2020-05-28T10:22:01.457+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
   about to fork child process, waiting until server is ready for connections.
   forked process: 11
   child process started successfully, parent exiting
   ** Starting Meteor...
   saving: someObjectId"
       at Object.module.exports.Test saving and restoring capabilities via AppHooks (/home/runner/work/sandstorm/sandstorm/tests/tests/appHooks.js:47:13)
       at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by zenhack** [comment]
Huh, I guess at some point the reason for this failure changed -- at one point or another I had it passing consistently locally (presumably when I wrote it...), but due to #3225 it was failing in CI. I'd just been assuming it was an artifact of that issue, but you're right it's clearly getting further than that. I'll dig into it soonish.
