### ISSUE TITLE
Unhandled exception in Promise: TypeError: Cannot read property 'catch' of undefined

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/sandstorm#3443]
Not sure if this causes me any actual problems, but it's spamming in my System Log, I thought it was at least potentially novel and interesting?

```
Unhandled exception in Promise:  TypeError: Cannot read property 'catch' of undefined
    at imports/server/backend.js:91:14
    at imports/server/async-helpers.ts:24:17
    at imports/server/async-helpers.ts:12:3
    at runWithEnvironment (packages/meteor.js:1286:24)
    at packages/meteor.js:1299:14
    at imports/server/async-helpers.ts:22:5
    at new Promise (<anonymous>)
    at inMeteor (imports/server/async-helpers.ts:21:10)
    at SandstormBackend.useGrain (imports/server/backend.js:90:12)
    at imports/server/scheduled-job.js:89:23
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/meteor.js:550:25
    at runWithEnvironment (packages/meteor.js:1286:24)
```

...It'd still be nice if the log had timestamps so I had some idea when this happened, lol.

**Comment by zenhack** [comment]
I'm seeing this as well, actually. I suspect it's happening once an hour since the stack trace goes through scheduled-job.js and we're both running ttrss.

I believe I have a fix; will submit a pr shortly.
