### ISSUE TITLE
SandForms grains load endlessly

### ISSUE THREAD

**Issue by rasos** [sandstorm-io/sandstorm#3448]
We have some SandForms grains that do not load anymore. The wheel turns endlessly. Not all of them and also other grains are fine.

We just see in the log:

```
Error: failed to connect to [127.0.0.1:4002]
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:398:15)
    at new MongoConnection (packages/mongo/mongo_driver.js:213:1)
    at new MongoInternals.RemoteCollectionDriver (packages/mongo/remote_collection_driver.js:4:1)
    at Object.<anonymous> (packages/mongo/remote_collection_driver.js:38:1)
    at Object.defaultRemoteCollectionDriver (packages/underscore/underscore.js:750:1)
    at new Mongo.Collection (packages/mongo/collection.js:102:1)
    at AccountsServer.AccountsCommon (accounts_common.js:23:18)
    at new AccountsServer (accounts_server.js:16:5)
    at Package (globals_server.js:5:12)
    at /programs/server/packages/accounts-base.js:1814:4
    - - - - -
    at [object Object].<anonymous> (/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/server.js:556:74)
    at [object Object].emit (events.js:106:17)
    at [object Object].<anonymous> (/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
    at [object Object].emit (events.js:98:17)
    at Socket.<anonymous> (/programs/server/npm/npm-mongo/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:448:13)
sandstorm/sandstorm-http-bridge.c++:2250: warning: App isn't listening for TCP connections after 30 seconds. Continuing to attempt to connect; address->toString() = 127.0.0.1:8000
```

Any chance to recover that grain?

**Comment by ocdtrekkie** [comment]
It sounds like Mongo isn't coming up for some reason, I wonder if there's a mongo.log file somewhere in the grain backup that might tell us why.

The biggest issue is that SandForms is pretty abandoned as a project, I don't think I ever found contact info for the folks who worked on it... But I presume the data submitted is somewhere in there, and with a bit of reverse engineering it's probably possible to get at it. If you can fix the data files in the grain backup, you can restore the grain from the backup and it should run again.

**Comment by rasos** [comment]
Here is the `mongo.log` from the backuped grain:

```
Mon Oct  5 08:35:45.276 [initandlisten] MongoDB starting : pid=7 port=4002 dbpath=/var 64-bit host=sandbox
Mon Oct  5 08:35:45.276 [initandlisten] db version v2.4.9
Mon Oct  5 08:35:45.276 [initandlisten] git version: 29a7a6bac226e01df929347a7feafdc6f3d57a2c
Mon Oct  5 08:35:45.276 [initandlisten] build info: Linux zero 4.1.0-1-amd64 #1 SMP Debian 4.1.3-1 (2015-08-03) x86_64 BOOST_LIB_VERSION=1_49
Mon Oct  5 08:35:45.276 [initandlisten] allocator: tcmalloc
Mon Oct  5 08:35:45.276 [initandlisten] options: { bind_ip: "127.0.0.1", dbpath: "/var", fork: true, logpath: "/var/mongo.log", noauth: true, nohttpinterface: true, noprealloc: true, port: 4002 }
************** 
old lock file: /var/mongod.lock.  probably means unclean shutdown,
but there are no journal files to recover.
this is likely human error or filesystem corruption.
please make sure that your journal directory is mounted.
found 2 dbs.
see: http://dochub.mongodb.org/core/repair for more information
*************
Mon Oct  5 08:35:45.284 [initandlisten] exception in initAndListen: 12596 old lock file, terminating
Mon Oct  5 08:35:45.284 dbexit: 
Mon Oct  5 08:35:45.284 [initandlisten] shutdown: going to close listening sockets...
Mon Oct  5 08:35:45.284 [initandlisten] shutdown: going to flush diaglog...
Mon Oct  5 08:35:45.284 [initandlisten] shutdown: going to close sockets...
Mon Oct  5 08:35:45.284 [initandlisten] shutdown: waiting for fs preallocator...
Mon Oct  5 08:35:45.284 [initandlisten] shutdown: lock for final commit...
Mon Oct  5 08:35:45.284 [initandlisten] shutdown: final commit...
Mon Oct  5 08:35:45.284 [initandlisten] shutdown: closing all files...
Mon Oct  5 08:35:45.285 [initandlisten] closeAllFiles() finished
Mon Oct  5 08:35:45.285 dbexit: really exiting now
```
The journal folder is empty. I assume it is the mongo inside the grain container which has an issue.

**Comment by zenhack** [comment]
Yes, that's my reading of it as well; it looks like sandform's db is possibly corrupted. The docs:

https://docs.mongodb.com/v2.4/tutorial/recover-data-following-unexpected-shutdown/

suggest that doing `mongod --repair` might help, but that needs to be run inside the grain... I wish we had something like `vagrant-spk enter-grain` for apps not in dev mode.

**Comment by ocdtrekkie** [comment]
Presumably you'd want to use the same version of Mongo to run that command on the extracted grain backup data, then put it back inside the grain backup zip and restore it as a new grain.

I agree an inline solution would be really nice, @zenhack. Perhaps the first step of that would be moving enter-grain out of vagrant-spk to Sandstorm itself, such that we could then devise additional rules in which to allow it to be used?

**Comment by zenhack** [comment]
We should separate it out into a stand-alone tool regardless of where it ends up landing.

Just a note, I had a look at the sandforms package, looks like this is old enough that it's running niscudb, so the command would actually be `niscud --repair` in this case.

But, ideally someone would push an update to sandforms that fixes whatever issue allowed this to happen, and recovered the data itself (perhaps by running that command). If the app is abandoned upstream though, that is perhaps unlikely to happen unless someone wants to take over maintenance (of the code, not just the package).
