### ISSUE TITLE
webkey authentication error returns stack trace

### ISSUE THREAD

**Issue by aerth** [sandstorm-io/sandstorm#3482]
This happens when I give an invalid password at the prompt after doing a `git pull` using the gogs clone address:
It does not happen when I don't give a password.

No password, output is good:
```
remote: Missing or invalid authorization header.
remote: 
remote: This address serves APIs, which allow external apps (such as a phone app) to
remote: access data on your Sandstorm server. This address is not meant to be opened
remote: in a regular browser.
fatal: Authentication failed for 'https://123456@api-123.hostname.example/user/repo.git/'
```

Incorrect password, returns stack trace and a 500 status code
```
remote: ERROR: The server threw an exception. Details:
remote: 
remote: (remote):0: failed: remote exception: remote exception: Error: Invalid authorization token [403]
remote:     at validateWebkey (imports/server/gateway-router.js:134:11)
remote:     at imports/server/gateway-router.js:409:7
remote:     at imports/server/async-helpers.ts:24:17
remote:     at imports/server/async-helpers.ts:12:3
remote:     at runWithEnvironment (packages/meteor.js:1286:24)
remote:     at packages/meteor.js:1299:14
remote:     at imports/server/async-helpers.ts:22:5
remote:     at new Promise (<anonymous>)
remote:     at inMeteor (imports/server/async-helpers.ts:21:10)
remote:     at GatewayRouterImpl.openApiSession (imports/server/gateway-router.js:403:12)
remote:     at /node_modules/capnp.js:174:21
remote:     at /programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
remote: stack: XXXX XXXX
fatal: unable to access 'https://123456@api-123.hostname.example/user/repo.git/': The requested URL returned error: 500

```

**Comment by zenhack** [comment]
Looks like this is the source of the problem:

https://github.com/sandstorm-io/sandstorm/blob/f430b94983d693392441b667ad22993c4272b31d/shell/imports/server/gateway-router.js#L461

Probably we just want to return an instance of ApiSession that responds to everything with the specified status code.
