### ISSUE TITLE
Exception while invoking method 'saveOrganizationSettings' Error: Match error: Missing key 'oidc' in field membership

### ISSUE THREAD

**Issue by greenrd** [sandstorm-io/sandstorm#3484]
I am running setup on an AWS EC2 instance, and I have added only Google as a login provider, and when I click "Save and Continue" on the Organization page of the setup wizard, I get the error `Failed to save change: Match failed [400]`

In the log file there is this error:

```
Exception while invoking method 'saveOrganizationSettings' Error: Match error: Missing key 'oidc' in field membership
    at check (packages/check/match.js:36:17)
    at MethodInvocation.saveOrganizationSettings (imports/server/admin-server.js:123:5)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
Sanitized and reported to the client as: errorClass [Error]: Match failed [400]
    at errorClass.<anonymous> (packages/check/match.js:91:27)
    at new errorClass (packages/meteor.js:655:17)
    at check (packages/check/match.js:36:17)
    at MethodInvocation.saveOrganizationSettings (imports/server/admin-server.js:123:5)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
    at packages/ddp-server/livedata_server.js:719:19
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:717:46
    at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
    at packages/ddp-server/livedata_server.js:715:46
    at new Promise (<anonymous>)
    at Session.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43 {
  isClientSafe: true,
  error: 400,
  reason: 'Match failed',
  details: undefined,
  errorType: 'Meteor.Error'
}
```

**Comment by zenhack** [comment]
Ack, we really need better testing for the setup wizard in particular. Anyway, thanks for the report, I've found the problem and will have fix soon.

**Comment by ocdtrekkie** [comment]
@greenrd Release 0.278 should fix this issue. Sandstorm should update within 24 hours, or you should be able to manually `sudo sandstorm update dev` to force it immediately, so that you can complete the setup wizard.
