### ISSUE TITLE
libssl.so.1.1 error in newest WeKan for Sandstorm

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/sandstorm#3600]
Hi,
today is released Node.js 12.22.9 that I added to wekan-5.91.spk package, when building it on Kubuntu 21.10 amd64:
https://releases.wekan.team/sandstorm/

But when I test wekan-5.91.spk package on my laptop at http://local.sandstorm.io:6080 , WeKan does not start and gives these errors:
```
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
node: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
** HTTP-BRIDGE: App server exited with status code: 127
** SANDSTORM SUPERVISOR: App exited with status code: 1
```

**Comment by ocdtrekkie** [comment]
So it sounds to me that libssl isn't being included in your build... which is weird if you didn't change anything relevant?

**Comment by xet7** [comment]
Hmm, Kubuntu seems to have libssl installed:
```
$ dpkg -l | grep libssl

ii  libssl1.1:amd64                                             1.1.1l-1ubuntu1.1                                       amd64        Secure Sockets Layer toolkit - shared libraries
```

**Comment by xet7** [comment]
I did change to newer npm packages but I don't know can that affect libssl

**Comment by xet7** [comment]
Does this need some LD_LIBRARY_PATH stuff?
https://www.bswen.com/2018/11/others-Openssl-version-cause-error-when-loading-shared-libraries-libssl.so.1.1.html

**Comment by xet7** [comment]
I changed distro from Kubuntu back to Mint, and it did not help. Well, that Mint is newer version that is previously was.

That newest WeKan v5.93 is still broken.

**Comment by ocdtrekkie** [comment]
Sorry I haven't been able to look into this as of yet. I've been a bit occupied in my personal life. Because you use meteor-spk, it's usually pretty weird for something to fail to be included. (And your alwaysInclude is `alwaysInclude = [ "." ],` which I take to mean "literally everything".

@zenhack Any chance you might have some insight what to try or look for on this one?

**Comment by zenhack** [comment]
Does that file (libssl.so.1.1) appear in your sandstorm-files.list? If, so what is the full path?

**Comment by ocdtrekkie** [comment]
@zenhack That's the weird part: meteor-spk doesn't use sandstorm-files.list, or generate one.

**Comment by zenhack** [comment]
Does a file by that exact name exist anywhere on the system?

What is the output of `ldd` on the node executable that is being used?

**Comment by xet7** [comment]
@zenhack 

```
wekan@hx:~$ node -v
v12.22.9

wekan@hx:~$ ldd /home/wekan/.volta/bin/node
        linux-vdso.so.1 (0x00007ffc9a62f000)
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f863f0db000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f863ee00000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f863ebd8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f863f8dc000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f863ebd3000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f863ebb9000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f863ebb4000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f863ebad000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f863eac9000)
```

**Comment by xet7** [comment]
@zenhack 

This is at Kubuntu:
```
wekan@hx:~$ uname -a
Linux hx 5.13.0-27-generic #29-Ubuntu SMP Wed Jan 12 17:36:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

wekan@hx:~$ cat /etc/issue
Ubuntu 21.10 \n \l
```

**Comment by zenhack** [comment]
I think meteor bundles its own copy of node; can you find that and report the output of `ldd` on that?

**Comment by xet7** [comment]
@zenhack 

It depends when I find it. I have always used newest available node, installed it with n or npm, and copied to meteor-spk at http://releases.wekan.team/meteor-spk/ .

That above script calls this install Sandstorm with this:
https://github.com/wekan/wekan/blob/master/releases/install-sandstorm.sh

And build spk with this:
https://github.com/wekan/wekan/blob/master/releases/release-sandstorm.sh

I run that build spk script from this more general many bundle build script:
https://github.com/wekan/wekan/blob/master/releases/release.sh

I tried previous Node 12.22.8 and it also had libssl.so.1.1 error.

I'll try to find does Meteor has specific node binary modifications.

**Comment by xet7** [comment]
Hmm, actually, I'll look if meteor-spk directory tree is missing some files. Just a moment.

**Comment by xet7** [comment]
Hmm, I don't see libssl there, I'll try to copy
```
~/projects/meteor-spk/meteor-spk-0.5.1/meteor-spk.deps/lib/x86_64-linux-gnu$ ls
ld-2.28.so    libc.so.6      libdl.so.2     libm-2.28.so  libpthread-2.28.so  librt-2.28.so  libz.so.1
libc-2.28.so  libdl-2.28.so  libgcc_s.so.1  libm.so.6     libpthread.so.0     librt.so.1     libz.so.1.2.11
```

**Comment by xet7** [comment]
I copied libssl, libgcc, libcrypto. It seems I need to copy glibc. Just a moment.
```
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /lib/x86_64-linux-gnu/libcrypto.so.1.1)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libcrypto.so.1.1)
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /lib/x86_64-linux-gnu/libgcc_s.so.1)
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: App exited with status code: 1
```

**Comment by xet7** [comment]
When I look at sandstorm directories, those with red are broken symlinks. So maybe I should build WeKan .spk on Debian or something else where those symlinks would not be broken.

![broken-symlinks](https://user-images.githubusercontent.com/15545/150426633-98d4914e-406a-4094-a00a-087b62fa594f.png)

**Comment by xet7** [comment]
Originally, before adding libssl.so.1.1 etc, these are broken symlinks in current meteor-spk on Kubuntu:

![broken-meteor-spl](https://user-images.githubusercontent.com/15545/150427234-7aec8f0b-267e-44e2-b8bc-2bab4fcf4523.png)

**Comment by xet7** [comment]
tammi = January, huhti = April

**Comment by zenhack** [comment]
Ok, so this makes a bit more sense to me; normal spk dev would likely pick up all the needed library dependencies, but since meteor-spk doesn't use the autodetection and just picks up the meteor dev bundle, if you've copied in an alternate version of node that links to system libraries, those won't be picked up.

FWIW, there is a meteor-spk 0.6.0 now, which includes a somewhat more recent version of node (14 I think?). If that's new enough for you, that may be the easiest path forwards. I suspect helping to keep meteor-spk up to date would be easier than than fighting with errors like these; see e.g. https://github.com/sandstorm-io/meteor-spk/pull/40 which was all it took to update meteor the last time.

**Comment by xet7** [comment]
@zenhack 

Oh, I did not notice version change, and that Node 14 is available, this issue is still open https://github.com/sandstorm-io/meteor-spk/issues/39

WeKan currently uses Node 12, but there is trying to upgrade to Node 14.

**Comment by xet7** [comment]
Using meteor-spk 0.6.0, newest Meteor, and WeKan branch that uses Node 14 but does not yet fully work, I get these errors. Fibers error could also be from some previous Node 12 WeKan, I'm not sure.

MongoDB compatibility error could maybe be related to https://github.com/meteor/meteor/issues/11666

```
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2022-02-04T22:55:49.133+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 11
child process started successfully, parent exiting
** Starting Meteor...
## There is an issue with `node-fibers` ##
`/programs/server/node_modules/fibers/bin/linux-x64-83-glibc/fibers.node` is missing.

Try running this to fix the issue: node /programs/server/node_modules/fibers/build
Error: Cannot find module '/programs/server/node_modules/fibers/bin/linux-x64-83-glibc/fibers'
Require stack:
- /programs/server/node_modules/fibers/fibers.js
- /programs/server/boot.js
- /main.js
- /start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/programs/server/node_modules/fibers/fibers.js:14:39)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.Mp._compile (/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Module.Mp.load (/programs/server/runtime.js:15:31)
/programs/server/node_modules/fibers/fibers.js:23
		throw new Error('Missing binary. See message above.');
		^

Error: Missing binary. See message above.
    at Object.<anonymous> (/programs/server/node_modules/fibers/fibers.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.Mp._compile (/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Module.Mp.load (/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/programs/server/boot.js:2:15)
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2022-02-04T22:55:49.597+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 11
child process started successfully, parent exiting
** Starting Meteor...
## There is an issue with `node-fibers` ##
`/programs/server/node_modules/fibers/bin/linux-x64-83-glibc/fibers.node` is missing.

Try running this to fix the issue: node /programs/server/node_modules/fibers/build
Error: Cannot find module '/programs/server/node_modules/fibers/bin/linux-x64-83-glibc/fibers'
Require stack:
- /programs/server/node_modules/fibers/fibers.js
- /programs/server/boot.js
- /main.js
- /start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/programs/server/node_modules/fibers/fibers.js:14:39)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.Mp._compile (/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Module.Mp.load (/programs/server/runtime.js:15:31)
/programs/server/node_modules/fibers/fibers.js:23
		throw new Error('Missing binary. See message above.');
		^

Error: Missing binary. See message above.
    at Object.<anonymous> (/programs/server/node_modules/fibers/fibers.js:23:9)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module.Mp._compile (/programs/server/runtime.js:50:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Module.Mp.load (/programs/server/runtime.js:15:31)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/programs/server/boot.js:2:15)
** HTTP-BRIDGE: App server exited with status code: 1
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.
** SANDSTORM SUPERVISOR: Grain no longer in use; shutting down.
** SANDSTORM SUPERVISOR: Starting up grain. Sandbox type: userns
** Starting Mongo...
2022-02-04T23:21:20.401+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 11
child process started successfully, parent exiting
** Starting Meteor...
sandstorm/sandstorm-http-bridge.c++:2837: warning: App isn't listening for TCP connections after 30 seconds. Continuing to attempt to connect; address->toString() = 127.0.0.1:4000
/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^

MongoServerSelectionError: Server at 127.0.0.1:4001 reports maximum wire version 3, but this version of the Node.js Driver requires at least 6 (MongoDB 3.6)
    at Timeout._onTimeout (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      '127.0.0.1:4001' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: '127.0.0.1', port: 4001 },
        address: '127.0.0.1:4001',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 134003682,
        lastWriteDate: 0,
        error: MongoCompatibilityError: Server at 127.0.0.1:4001 reports maximum wire version 3, but this version of the Node.js Driver requires at least 6 (MongoDB 3.6)
            at checkSupportedServer (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:62:12)
            at /programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:106:40
            at MessageStream.messageHandler (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:474:9)
            at MessageStream.emit (events.js:400:28)
            at processIncomingData (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
            at MessageStream._write (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
            at writeOrBuffer (internal/streams/writable.js:358:12)
            at MessageStream.Writable.write (internal/streams/writable.js:303:10)
            at Socket.ondata (internal/streams/readable.js:726:22)
            at Socket.emit (events.js:400:28)
            at addChunk (internal/streams/readable.js:290:12)
            at readableAddChunk (internal/streams/readable.js:265:9)
            at Socket.Readable.push (internal/streams/readable.js:204:10)
            at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  }
}
** HTTP-BRIDGE: App server exited with status code: 1
*** lost connection to grain (probably because it shut down) ***
```

**Comment by xet7** [comment]
I got WeKan working with this fix https://github.com/sandstorm-io/meteor-spk/pull/41
