### ISSUE TITLE
Sandstorm WeKan Meteor 2.7.2 error

### ISSUE THREAD

**Issue by xet7** [sandstorm-io/sandstorm#3618]
Hi,
any idea what I should try to do? This is with WeKan on Sandstorm Experimental App Market.
```
** Starting Mongo...
2022-05-17T11:15:03.975+0000 I STORAGE  Engine custom option: log=(prealloc=false,file_max=200KB)
about to fork child process, waiting until server is ready for connections.
forked process: 11
child process started successfully, parent exiting
** Starting Meteor...
sandstorm/sandstorm-http-bridge.c++:2837: warning: App isn't listening for TCP connections after 30 seconds. Continuing to attempt to connect; address->toString() = 127.0.0.1:4000
/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^

MongoServerSelectionError: Server at 127.0.0.1:4001 reports maximum wire version 3, but this version of the Node.js Driver requires at least 6 (MongoDB 3.6)
    at Timeout._onTimeout (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/sdam/topology.js:312:38)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  reason: TopologyDescription {
    type: 'Unknown',
    servers: Map(1) {
      '127.0.0.1:4001' => ServerDescription {
        _hostAddress: HostAddress { isIPv6: false, host: '127.0.0.1', port: 4001 },
        address: '127.0.0.1:4001',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 7958995,
        lastWriteDate: 0,
        error: MongoCompatibilityError: Server at 127.0.0.1:4001 reports maximum wire version 3, but this version of the Node.js Driver requires at least 6 (MongoDB 3.6)
            at checkSupportedServer (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:62:12)
            at /programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connect.js:106:40
            at MessageStream.messageHandler (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/connection.js:474:9)
            at MessageStream.emit (events.js:400:28)
            at processIncomingData (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:108:16)
            at MessageStream._write (/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/cmap/message_stream.js:28:9)
            at writeOrBuffer (internal/streams/writable.js:358:12)
            at MessageStream.Writable.write (internal/streams/writable.js:303:10)
            at Socket.ondata (internal/streams/readable.js:726:22)
            at Socket.emit (events.js:400:28)
            at addChunk (internal/streams/readable.js:290:12)
            at readableAddChunk (internal/streams/readable.js:265:9)
            at Socket.Readable.push (internal/streams/readable.js:204:10)
            at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    logicalSessionTimeoutMinutes: undefined
  }
}
** HTTP-BRIDGE: App server exited with status code: 1
*** lost connection to grain (probably because it shut down) ***
```

**Comment by xet7** [comment]
@ocdtrekkie 

Yes, I'll figure it out, migrate from Sandstorm's MongoDB version to something, etc.

I'll close this, because I will fix this myself later.
