### ISSUE TITLE
Email login giving error with a seemingly working SMTP server

### ISSUE THREAD

**Issue by jparyani** [sandstorm-io/sandstorm#421]
Reported by `itscassa` from IRC:
```
Exception while invoking method 'createAndEmailTokenForUser' Error: Greeting never received
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:326:15)
    at smtpSend (packages/sandstorm-email/email.js:99:1)
    at Object.SandstormEmail.rawSend (packages/sandstorm-email/email.js:172:1)
    at Object.SandstormEmail.send (packages/sandstorm-email/email.js:158:1)
    at sendTokenEmail (packages/accounts-email-token/token_server.js:110:1)
    at createAndEmailTokenForUser (packages/accounts-email-token/token_server.js:159:1)
    at [object Object].Meteor.methods.createAndEmailTokenForUser (packages/accounts-email-token/token_server.js:172:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1599:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    - - - - -
    at SMTPClient.<anonymous> (/programs/server/npm/sandstorm-email/node_modules/simplesmtp/lib/client.js:268:25)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

**Comment by bauyrzhanrustemov** [comment]
Did you figure it out? I have the same error. Please, help me if you find the answer.

**Comment by opbt-hog** [comment]
Same problem here hosting on Galaxy platform. Works fine at Modulus and other servers.

**Comment by opbt-hog** [comment]
Using port 587 instead of 25 fixed the issue for me.

**Comment by paulproteus** [comment]
Great! FWIW, I'd be surprised and impressed if Galaxy runs Sandstorm
properly. I'd love to hear from you about how that's going.
