### ISSUE TITLE
Be clearer that SMTP server must be a relay

### ISSUE THREAD

**Issue by ar-jan** [sandstorm-io/sandstorm#531]
I'm trying to get login via email working, but I'm running into a problem.

- I've configured an external SMTP server like `smtp://user:pass@host:port`  under Admin settings.
- I can successfully send an invite using these settings via Send invite > Send an e-mail, using the same SMTP user's email address as sender
- I've only configured the extern SMTP url, no SMTP proxy, which seems like it should be sufficient to get login / auth emails sent from Sandstorm
- But, both the SMTP Url "Test" option as well as the "Send Login Email" on a `Claim Invite` page give `mailbox unavailable` / `Sender address is not allowed` errors in /opt/sandstorm/var/log/sandstorm.log:

When trying to do `Send Login Email` after following an invite link (using the same email address the invite was sent to):

> Exception while invoking method 'createAndEmailTokenForUser' SenderError: Mail from command failed - 550-Requested action not taken: mailbox unavailable
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:398:15)
    at smtpSend (packages/sandstorm-email/email.js:101:1)
    at Object.SandstormEmail.rawSend (packages/sandstorm-email/email.js:176:1)
    at Object.SandstormEmail.send (packages/sandstorm-email/email.js:161:1)
    at sendTokenEmail (packages/accounts-email-token/token_server.js:110:1)
    at createAndEmailTokenForUser (packages/accounts-email-token/token_server.js:159:1)
    at [object Object].Meteor.methods.createAndEmailTokenForUser (packages/accounts-email-token/token_server.js:172:1)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    - - - - -
550 Sender address is not allowed.
    at SMTPClient._actionMAIL (/programs/server/npm/sandstorm-email/node_modules/simplesmtp/lib/client.js:879:23)
    at SMTPClient._onData (/programs/server/npm/sandstorm-email/node_modules/simplesmtp/lib/client.js:329:29)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
    at process._tickCallback (node.js:442:13)

When trying to do the SMTP Url `Test` under Admin settings:

> Exception while invoking method 'testSend' SenderError: Mail from command failed - 550-Requested action not taken: mailbox unavailable
    at Object.Future.wait (/programs/server/node_modules/fibers/future.js:398:15)
    at smtpSend (packages/sandstorm-email/email.js:101:1)
    at Object.SandstormEmail.rawSend (packages/sandstorm-email/email.js:176:1)
    at Object.SandstormEmail.send (packages/sandstorm-email/email.js:161:1)
    at [object Object].Meteor.methods.testSend (app/shared/admin.js:710:22)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    - - - - -
550 Sender address is not allowed.
    at SMTPClient._actionMAIL (/programs/server/npm/sandstorm-email/node_modules/simplesmtp/lib/client.js:879:23)
    at SMTPClient._onData (/programs/server/npm/sandstorm-email/node_modules/simplesmtp/lib/client.js:329:29)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
    at process._tickCallback (node.js:442:13)

So should what I want be possible (as I surely hope), or is sending the actual invite bypassing your sender address restrictions?

**Comment by ar-jan** [comment]
P.S. It's a 3rd party email address, not using the same domain as my sandstorm install.

**Comment by kentonv** [comment]
Hi Arjan,

Both the "test SMTP" and the email login functions are sent from `no-reply@<your-sandstorm-host>`, whereas the "send invite" functionality sets the From address to the address you specify (by default, the address attached to your account, i.e. your personal address). My guess is that your SMTP server is configured to permit only sending using your own address as the "from". For Sandstorm, you will need to configure your SMTP server to relay any mail that Sandstorm sends to it -- this will also be needed in order to allow people to use mail apps on your server. Note that this implies that, say, gmail's SMTP functionality is not appropriate for Sandstorm, since it only allows you to send mail as a single user; you need a real SMTP relay.

If you don't want to set up an SMTP server yourself, one alternative is to get an account with Mailgun, Mandrill, or Sendgrid. These services all specialize in being an SMTP relay (with proper spam controls) and some of them have free tiers.

Eventually we'd like Sandstorm to act as a general SMTP relay itself, but one problem with this is that machines on IaaS services (e.g. AWS) as well as consumer internet IPs are generally all blacklisted for spam, so unless you own an unsullied IP address you can use, these days you kind of have to go through one of the mail delivery services.

**Comment by ar-jan** [comment]
Thanks, that makes sense. I'd read about the recommendation to use an SMTP relay service, but I thought this was mainly required for email apps, and that the email invite could use the SMTP server's associated email address (perhaps because the [email wiki](https://github.com/sandstorm-io/sandstorm/wiki/Configuring-your-server-for-email) mentions using an email address as SMTP login name, which I thought unlikely to be the case for an actual SMTP relay).

The way it actually works makes sense, but perhaps it would still be a good idea to make the help text in the UI more explicit about the fact that it must be an SMTP relay server authorized for sending from your sandstorm hostname / domain?

**Comment by kentonv** [comment]
Sounds reasonable.

**Comment by ar-jan** [comment]
The current text is:
> Address of an SMTP (email) server, like smtp://user:pass@host:port. This will be used by email apps and to send email invites.

How about this?
> Address of an SMTP relay server configured to send email from your Sandstorm hostname, like smtp://user:pass@host:port. This will be used by email apps and to send email invites.

**Comment by kpreid** [comment]
"…configured to _allow sending_ from your…", otherwise it sounds like the server _chooses_ the address, which it doesn't.

**Comment by ar-jan** [comment]
Right, I've updated my comment.

**Comment by ar-jan** [comment]
Was done in #568.
