### ISSUE TITLE
"vagrant-spk up" went boom with a weird Puppet error

### ISSUE THREAD

**Issue by yozlet** [sandstorm-io/sandstorm#536]
This was when trying to do the packaging tutorial. I'd already successfully cloned and run Sandstorm dev server.

On Mac OS X 10.10.3, with VirtualBox:

```
==> default: Successfully added box 'debian/jessie64' (v8.1.0) for 'virtualbox'!
==> default: Importing base box 'debian/jessie64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'debian/jessie64' is up to date...
==> default: Setting the name of the VM: sandstorm_default_1435110461987_57032
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 6080 => 6080 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /opt/app => /Users/yoz/Code/php-app-to-package-for-sandstorm
    default: /vagrant => /Users/yoz/Code/php-app-to-package-for-sandstorm
    default: /host-dot-sandstorm => /Users/yoz/.sandstorm
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> default:                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:--
==> default: --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 -
==> default: -:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 -
==> default: -:--:--     0
100 53945  100 53945    0     0   9117      0  0:00:05  0:00:05 --:--:-- 12232
==> default:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
==> default:                                  Dload  Upload   Total   Spe
==> default: nt    Left  Speed
  0     0    0     0    0     0
==> default:  0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
  0 19.0M    0 15797    0     0   2776      0  1:59:43  0:00:05  1:59:38  3789
  5 19.0M    5 1151k    0     0   172k      0  0:01:53  0:00:06  0:01:47  276k
 11 19.0M   11 2307k    0     0   300k      0  0:01:04  0:00:07  0:00:57  554k
 18 19.0M   18 3571k    0     0   411k      0  0:00:47  0:00:08  0:00:39  859k
 25 19.0M   25 5019k    0     0   518k      0  0:00:37  0:00:09  0:00:28 1207k
 35 19.0M   35 6871k    0     0   642k      0  0:00:30  0:00:10  0:00:20 1371k
 47 19.0M   47 9291k    0     0   794k      0  0:00:24  0:00:11  0:00:13 1627k
 61 19.0M   61 11.6M    0     0   942k      0  0:00:20  0:00:12  0:00:08 1928k
 78 19.0M   78 14.9M    0     0  1115k      0  0:00:17  0:00:13  0:00:04 2338k
 96 19.0M   96 18.2M    0     0  1274k      0  0:00:15  0:00:14  0:00:01 2739k
100 19.0M  100 19.0M    0     0  1302k      0  0:00:14  0:00:14 --:--:-- 2952k
==> default: Sandstorm requires sysctl kernel.unprivileged_userns_clone to be enabled.
==> default: Currently, it is not enabled on your system.
==> default: Note: Sandstorm's storage will only be accessible to the group 'sandstorm'.
==> default:
==> default: Config written to /opt/sandstorm/sandstorm.conf.
==> default: created: /usr/local/bin/spk
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/sandstorm.service to /etc/systemd/system/sandstorm.service.
==> default: Setup complete. You should configure the site at:
==> default:   http://local.sandstorm.io:6080/admin/settings/dfc7283218acb4bab02f6125422f81d36980b6b8
==> default: WARNING: This token expires in 15 minutes.
==> default: You can generate a new token by running 'sandstorm admin-token' from the command line
==> default:
==> default: To learn how to control the server, run:
==> default:   sandstorm help
==> default: ALLOW_DEV_ACCOUNTS=true
==> default: Failed to stop puppet.service: Unit puppet.service not loaded.
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

chmod +x /tmp/vagrant-shell && /tmp/vagrant-shell

Stdout from the command:

Sandstorm requires sysctl kernel.unprivileged_userns_clone to be enabled.
Currently, it is not enabled on your system.
Note: Sandstorm's storage will only be accessible to the group 'sandstorm'.

Config written to /opt/sandstorm/sandstorm.conf.
created: /usr/local/bin/spk
Setup complete. You should configure the site at:
  http://local.sandstorm.io:6080/admin/settings/dfc7283218acb4bab02f6125422f81d36980b6b8
WARNING: This token expires in 15 minutes.
You can generate a new token by running 'sandstorm admin-token' from the command line

To learn how to control the server, run:
  sandstorm help
ALLOW_DEV_ACCOUNTS=true


Stderr from the command:

stdin: is not a tty
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 53945  100 53945    0     0   9117      0  0:00:05  0:00:05 --:--:-- 12232
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.0M  100 19.0M    0     0  1302k      0  0:00:14  0:00:14 --:--:-- 2952k
Created symlink from /etc/systemd/system/multi-user.target.wants/sandstorm.service to /etc/systemd/system/sandstorm.service.
Failed to stop puppet.service: Unit puppet.service not loaded.

Traceback (most recent call last):
  File "/usr/local/bin/vagrant-spk", line 776, in <module>
    main()
  File "/usr/local/bin/vagrant-spk", line 773, in main
    operation(args)
  File "/usr/local/bin/vagrant-spk", line 696, in bring_up_vm
    call_vagrant_command(sandstorm_dir, "up")
  File "/usr/local/bin/vagrant-spk", line 617, in call_vagrant_command
    return subprocess.check_call(command, cwd=sandstorm_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['vagrant', 'up']' returned non-zero exit status 1
```

My environment:

```
declare -x Apple_PubSub_Socket_Render="/private/tmp/com.apple.launchd.QfoDbuIBI9/Render"
declare -x COLORFGBG="7;0"
declare -x HOME="/Users/yoz"
declare -x HOMEBREW_CASK_OPTS="--appdir=/Applications"
declare -x ITERM_PROFILE="Default"
declare -x ITERM_SESSION_ID="w0t0p0"
declare -x LANG="en_US.UTF-8"
declare -x LOGNAME="yoz"
declare -x OLDPWD="/Users/yoz/Code"
declare -x PATH="/Users/yoz/.rbenv/shims:/usr/local/bin:/usr/local/mysql/bin:/usr/bin:/bin:/usr/sbin:/sbin"
declare -x PWD="/Users/yoz/Code/php-app-to-package-for-sandstorm"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_AUTH_SOCK="/private/tmp/com.apple.launchd.sjO8IJ3oJG/Listeners"
declare -x TERM="xterm-256color"
declare -x TERM_PROGRAM="iTerm.app"
declare -x TMPDIR="/var/folders/vm/6y4_pqjs01x_pvd213p42bj80000gn/T/"
declare -x USER="yoz"
declare -x XPC_FLAGS="0x0"
declare -x XPC_SERVICE_NAME="0"
declare -x __CF_USER_TEXT_ENCODING="0x1F5:0x0:0x0"
```

**Comment by yozlet** [comment]
When running Sandstorm Showcase after this, we realised that MySQL hadn't been provisioned properly:

```
...** SANDSTORM SUPERVISOR: Starting up grain.
/opt/app/.sandstorm/launcher.sh: line 16: /usr/bin/mysql_install_db: No such file or directory
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
/opt/app/.sandstorm/launcher.sh: line 19: /usr/sbin/mysqld: No such file or directory
/opt/app/.sandstorm/launcher.sh: line 20: /usr/sbin/php5-fpm: No such file or directory
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
waiting for mysql to be available at /var/run/mysqld/mysqld.sock
```

**Comment by zarvox** [comment]
Thanks for reporting this!

It looks like Debian's Vagrant box maintainers upstream removed the puppet provisioner by default, so we no longer need to stop it explicitly to save RAM.  I've fixed the issue in vagrant-spk: https://github.com/sandstorm-io/vagrant-spk/commit/a4dcf73a10742b9b40018ea59bbfdfabe4bbaeea

Try pulling the latest `vagrant-spk`, then running `vagrant-spk wipe` in the `php-app-to-package-for-sandstorm` folder, then running through the packaging tutorial again, starting from the `vagrant-spk setupvm lemp` step.
