### ISSUE TITLE
Better logging for this SMTP failure

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/sandstorm#615]
Received this exception when attempting to test my SMTP settings:

Exception while invoking method 'testSend' Error: getaddrinfo ENOTFOUND
    at Object.Future.wait
(/programs/server/node_modules/fibers/future.js:398:15
)
    at smtpSend (packages/sandstorm-email/email.js:101:1)
    at Object.SandstormEmail.rawSend
(packages/sandstorm-email/email.js:176:1)
    at Object.SandstormEmail.send (packages/sandstorm-email/email.js:161:1)
    at [object Object].Meteor.methods.testSend (app/shared/admin.js:871:22)
    at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
    at packages/ddp/livedata_server.js:648:1
    at [object Object]._.extend.withValue
(packages/meteor/dynamics_nodejs.js:56
:1)
    at packages/ddp/livedata_server.js:647:1
    at [object Object]._.extend.withValue
(packages/meteor/dynamics_nodejs.js:56
:1)
    - - - - -
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)

I exhaustively tested my ability to reach smtp.mailgun.org and various other domain names in the course of attempting to resolve this. After a rebuild of the VM the issue has gone away, but since that error is along a major test path that many new users will take, it might be wise to catch it and report the specific domain name that can't be found.

Thanks!

**Comment by paulproteus** [comment]
Hi Nolan! Thanks for filing this.

A question for you -- where are you running Sandstorm? On Digital Ocean?
Vagrant + VirtualBox? etc.

Knowing that might help me get to the bottom of this faster.

**Comment by ndarilek** [comment]
In a stock Debian 8.1 VM.

But I'm a bit confused, can't you just find the callsite in your own
code, wrap it with a try, and simply report "Unable to resolve
foo.bar.com" instead of the exception? Just knowing what failed to
resolve would have gone a long way toward helping me to fix it.

The issue may have been that I changed /etc/hostname after starting
Sandstorm. Not sure from what to what, and whether it resolved or didn't
before.

Sorry, it'll be hard to retroactively troubleshoot, my hope was just to
get a better error report there.

Thanks.

**Comment by paulproteus** [comment]
Hi Nolan! I have two goals, and I realize I wasn't clear about them in my original reply.

1. I want to improve the error message, as you have requested.

2. Separately, I also want to see if I can understand why the `ENOTFOUND` error is occurring. It seems you're looking up a hostname that _does_ exist, so if possible, I'd like to be able to avoid the error rather than just improve the error message.

With that in mind, let me reply in more depth.

> In a stock Debian 8.1 VM.

Thanks for answering this! I meant to ask what hypervisor/virtual machine platform? Xen? VirtualBox+Vagrant? DigitalOcean? Amazon AWS?

For goal 2 (understand why ENOTFOUND is occurring), I'm trying to ask about your virtualization platform in case there's a systemic problem I should know about that causes `ENOTFOUND` to be more common. If so, then maybe I can come up with a fix.

> But I'm a bit confused, can't you just find the callsite in your own
> code, wrap it with a try, and simply report "Unable to resolve
> foo.bar.com" instead of the exception? Just knowing what failed to
> resolve would have gone a long way toward helping me to fix it.

Yes! This would help with goal 1, which is to improve the error message.

> The issue may have been that I changed /etc/hostname after starting
> Sandstorm. Not sure from what to what, and whether it resolved or didn't
> before.

Interesting! I can see about testing this situation.

Thanks for your quick replies!

**Comment by ndarilek** [comment]
Ah, sorry, didn't fully understand.

It's a stock Debian 8.1 VM running under KVM. Initially the hostname was
set to debian, which of course didn't resolve and triggered the error I
reported this morning. I then changed /etc/hostname to thewordnerd.info,
which does resolve, and did the install. During the install process, I
selected https://sandstorm.thewordnerd.info/*.sandstorm.thewordnerd.info
as my HTTP host/wildcard subdomain. I may or may not have changed
/etc/hostname again after that.

Sorry, that's about all I recall, consolidating a bunch of servers into
VMs on one dedicated server instance so I've been doing lots of
reshuffling recently.
