### ISSUE TITLE
Github auth broken in dev?

### ISSUE THREAD

**Issue by pwais** [sandstorm-io/sandstorm#675]
I'm using `vagrant-spk` and have and up-to-date dev install of sandstorm (at the time of writing).  I tried enabling Github auth in the admin console.  Setup works fine, but when I log out and try to log in using Github, login fails and I see this in `/opt/sandstorm/var/log/sandstorm.log`: 

```
Exception while invoking method 'login' Error: Match error: Expected string, got object in field name
    at checkSubtree (packages/check/match.js:159:1)
    at packages/check/match.js:296:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at checkSubtree (packages/check/match.js:290:1)
    at check (packages/check/match.js:32:1)
    at configurations (packages/sandstorm-db/user.js:81:1)
    at Object.Accounts.insertUserDoc (packages/accounts-base/accounts_server.js:999:1)
    at Object.Accounts.updateOrCreateUserFromExternalService (packages/accounts-base/accounts_server.js:1164:1)
    at [object Object].Package (packages/sandstorm-accounts-oauth/oauth_server.js:55:1)
    at packages/accounts-base/accounts_server.js:358:1
Sanitized and reported to the client as: Match failed [400]
```

Looks like Github is returning something with a schema that Sandstorm(/Meteor?) doesn't expect.

**Comment by paulproteus** [comment]
I can log in fine to your server.

**Comment by paulproteus** [comment]
I'll make you a build that logs your `name` and we can go from there!

**Comment by pwais** [comment]
ah-ha, so my github account was lacking a name at the time of testing.  i added a name and all works now.  https://www.destroyallsoftware.com/talks/wat
